# -*- coding: utf-8 -*-
# French translations for 441 citizenship page: options and book excerpts.
# Used by extract_441_questions.py to fill data-fr-options and data-fr-expl.

OPTIONS_EN_FR_EXTRA = {
    # Numbers / years (keep as-is or translate if phrase)
    "1867": "1867", "1967": "1967", "1982": "1982", "2000": "2000",
    "1066": "1066", "1215": "1215", "1497": "1497", "1608": "1608", "1763": "1763",
    "1776": "1776", "1793": "1793", "1833": "1833", "1865": "1865",
    "1000": "1000", "2010": "2010", "1817": "1817", "1813": "1813", "1849": "1849",
    # Royalty / government
    "Queen Elizabeth I": "La reine Elizabeth I",
    "Queen Elizabeth II": "La reine Elizabeth II",
    "King George VI": "Le roi George VI",
    "Prime Minister Trudeau": "Le premier ministre Trudeau",
    "Freedom and equality": "Liberté et égalité",
    "Peace and order": "Paix et ordre",
    "Peace, order and good government": "Paix, ordre et bon gouvernement",
    "Freedom and democracy": "Liberté et démocratie",
    "Whereas Canada is founded": "Attendu que le Canada est fondé",
    "Canada recognizes": "Le Canada reconnaît",
    "Whereas Canada is": "Attendu que le Canada est",
    "The Canadian Charter": "La Charte canadienne",
    "Right to move between provinces": "Droit de déménager entre les provinces",
    "Right to enter and leave Canada": "Droit d'entrer au Canada et d'en sortir",
    "Right to work anywhere in Canada": "Droit de travailler n'importe où au Canada",
    "Mobility rights, Aboriginal rights, Official language rights": "Droits à la mobilité, droits des Autochtones, droits linguistiques officiels",
    "Voting rights, Education rights, Health rights": "Droit de vote, droit à l'éducation, droit à la santé",
    "Property rights, Business rights, Tax rights": "Droits de propriété, droits commerciaux, droits fiscaux",
    "Mobility rights, Aboriginal rights, Official language rights, Multiculturalism rights": "Droits à la mobilité, droits des Autochtones, droits linguistiques officiels, droits du multiculturalisme",
    "Voting, Education, Health, Housing": "Vote, éducation, santé, logement",
    "Work, Property, Business, Tax": "Travail, propriété, commerce, impôt",
    "Individual rights": "Droits individuels",
    "Collective rights": "Droits collectifs",
    "Both individual and collective rights": "Droits individuels et collectifs",
    "Only federal rights": "Seulement les droits fédéraux",
    "Multiculturalism": "Multiculturalisme",
    "Bilingualism": "Bilinguisme",
    "Both multiculturalism and bilingualism": "Multiculturalisme et bilinguisme",
    "Monarchy": "Monarchie",
    "Obey the law, Take responsibility for oneself and family, Serve on a jury": "Respecter la loi, assumer ses responsabilités et celles de sa famille, siéger à un jury",
    "Pay taxes, Vote, Serve in military": "Payer des impôts, voter, servir dans l'armée",
    "Learn English, Work, Pay taxes": "Apprendre l'anglais, travailler, payer des impôts",
    "Optional": "Optionnel",
    "A privilege": "Un privilège",
    "A legal duty": "Un devoir juridique",
    "A voluntary service": "Un service volontaire",
    "Working in government": "Travailler au gouvernement",
    "Military service": "Service militaire",
    "Teaching": "Enseignement",
    "Business": "Commerce",
    "Magna Carta and Charter of Rights": "Magna Carta et Charte des droits",
    "Constitution and Charter of Rights": "Constitution et Charte des droits",
    "Magna Carta and Constitution": "Magna Carta et Constitution",
    "Bill of Rights and Charter": "Déclaration des droits et Charte",
    "First Nations, Métis, Inuit": "Premières Nations, Métis, Inuits",
    "Indians, Métis, Eskimos": "Indiens, Métis, Esquimaux",
    "Aboriginal, Native, Indigenous": "Autochtone, indigène, autochtone",
    "Tribes, Nations, Communities": "Tribus, nations, communautés",
    "People of mixed Aboriginal and European ancestry": "Personnes d'ascendance autochtone et européenne mixte",
    "First Nations people": "Peuples des Premières Nations",
    "Inuit people": "Peuple inuit",
    "French settlers": "Colons français",
    "The people": "Le peuple",
    "The land": "La terre",
    "The water": "L'eau",
    "The sky": "Le ciel",
    "John Cabot": "John Cabot",
    "Jacques Cartier": "Jacques Cartier",
    "Samuel de Champlain": "Samuel de Champlain",
    "French Parliament": "Parlement français",
    "British Parliament": "Parlement britannique",
    "Canadian Parliament": "Parlement canadien",
    "American Congress": "Congrès américain",
    "Quebec Act": "Acte de Québec",
    "Constitutional Act of 1791": "Acte constitutionnel de 1791",
    "British North America Act": "Acte de l'Amérique du Nord britannique",
    "Charter of Rights": "Charte des droits",
    "First Governor of Upper Canada": "Premier gouverneur du Haut-Canada",
    "First Prime Minister": "Premier premier ministre",
    "First Governor General": "Premier gouverneur général",
    "A military hero": "Un héros militaire",
    "Sir John A. Macdonald, George-Étienne Cartier, George Brown": "Sir John A. Macdonald, George-Étienne Cartier, George Brown",
    "William Lyon Mackenzie King, Pierre Trudeau, Lester Pearson": "William Lyon Mackenzie King, Pierre Trudeau, Lester Pearson",
    "John Cabot, Jacques Cartier, Samuel de Champlain": "John Cabot, Jacques Cartier, Samuel de Champlain",
    "From sea to sea": "D'un océan à l'autre",
    "A Mari Usque Ad Mare": "A Mari Usque Ad Mare",
    "The railway": "Le chemin de fer",
    "The highway": "L'autoroute",
    "The airplane": "L'avion",
    "The ship": "Le navire",
    "French community in Canada": "Communauté francophone au Canada",
    "International organization of French-speaking nations": "Organisation internationale des pays francophones",
    "Quebec language law": "Loi sur la langue au Québec",
    "A French colony": "Une colonie française",
    "He won Olympic gold": "Il a remporté l'or olympique",
    "He ran across Canada to raise money for cancer research": "Il a traversé le Canada à la course pour amasser des fonds pour la recherche sur le cancer",
    "He was a war hero": "Il était un héros de guerre",
    "He was a politician": "Il était un homme politique",
    "15th Governor General of Canada": "15e gouverneur général du Canada",
    "A famous writer": "Un écrivain célèbre",
    "First woman Prime Minister": "Première femme premier ministre",
    "First Black woman elected to the Nova Scotia legislature": "Première femme noire élue à l'Assemblée législative de la Nouvelle-Écosse",
    "First Governor General": "Premier gouverneur général",
    "A famous athlete": "Un athlète célèbre",
    "Canadian law": "Droit canadien",
    "British common law": "Common law britannique",
    "French civil law": "Droit civil français",
    "American law": "Droit américain",
    "Independence": "Indépendance",
    "Union of provinces": "Union des provinces",
    "Federal system": "Système fédéral",
    "Economic development": "Développement économique",
    "National unity": "Unité nationale",
    "Both economic development and national unity": "Développement économique et unité nationale",
    "Western expansion only": "Expansion vers l'ouest seulement",
    "Canada has a king or queen": "Le Canada a un roi ou une reine",
    "The monarch is the head of state": "Le monarque est le chef de l'État",
    "The monarch's powers are limited by the Constitution": "Les pouvoirs du monarque sont limités par la Constitution",
    "Executive, Legislative, Judicial": "Exécutif, législatif, judiciaire",
    "Federal, Provincial, Municipal": "Fédéral, provincial, municipal",
    "House of Commons, Senate, Courts": "Chambre des communes, Sénat, tribunaux",
    "Prime Minister, Governor General, Supreme Court": "Premier ministre, gouverneur général, Cour suprême",
    "Queen is head of state, PM is head of government": "La reine est le chef de l'État, le PM est le chef du gouvernement",
    "Queen makes laws, PM enforces them": "La reine fait les lois, le PM les applique",
    "No difference": "Aucune différence",
    "Queen is elected, PM is appointed": "La reine est élue, le PM est nommé",
    "Order of Canada": "Ordre du Canada",
    "Victoria Cross": "Croix de Victoria",
    "Medal of Honour": "Médaille d'honneur",
    "Prime Minister's Award": "Prix du premier ministre",
    "Mark an X next to your chosen candidate": "Mettez un X à côté du nom du candidat de votre choix",
    "Write the candidate's name": "Écrivez le nom du candidat",
    "Raise your hand": "Levez la main",
    "Press a button": "Appuyez sur un bouton",
    "Freedom of conscience and religion": "Liberté de conscience et de religion",
    "Freedom of thought, belief, opinion and expression": "Liberté de pensée, de croyance, d'opinion et d'expression",
    "Freedom of peaceful assembly and association": "Liberté de réunion et d'association pacifiques",
}

# More options (missing from first pass) – so all options show in FR when language=FR
OPTIONS_EN_FR_MISSING = {
    "10 provinces and 2 territories": "10 provinces et 2 territoires",
    "10 provinces and 3 territories": "10 provinces et 3 territoires",
    "9 provinces and 3 territories": "9 provinces et 3 territoires",
    "11 provinces and 3 territories": "11 provinces et 3 territoires",
    "20 minutes": "20 minutes",
    "30 minutes": "30 minutes",
    "45 minutes": "45 minutes",
    "60 minutes": "60 minutes",
    "60% (12 correct)": "60 % (12 bonnes réponses)",
    "70% (14 correct)": "70 % (14 bonnes réponses)",
    "75% (15 correct)": "75 % (15 bonnes réponses)",
    "80% (16 correct)": "80 % (16 bonnes réponses)",
    "A Canadian symbol": "Un symbole canadien",
    "A Prime Minister": "Un premier ministre",
    "A checkmark": "Une coche",
    "An X": "Un X",
    "A cultural agreement": "Un accord culturel",
    "A trade agreement": "Un accord commercial",
    "A dictatorship": "Une dictature",
    "A republic": "Une république",
    "A famous explorer": "Un explorateur célèbre",
    "A government body": "Un organisme gouvernemental",
    "A great surveyor and explorer": "Un grand arpenteur et explorateur",
    "A group of citizens who make decisions in court": "Un groupe de citoyens qui prennent des décisions au tribunal",
    "A group of judges": "Un groupe de juges",
    "A group of lawyers": "Un groupe d'avocats",
    "A military alliance": "Une alliance militaire",
    "A network helping slaves escape to freedom": "Un réseau aidant les esclaves à s'échapper vers la liberté",
    "A robotic arm for space shuttle": "Un bras robotique pour la navette spatiale",
    "A system where Parliament is the primary legislative body": "Un système où le Parlement est la principale instance législative",
    "A system where the King/Queen is head of state but power is limited by the constitution": "Un système où le roi/la reine est le chef de l'État mais le pouvoir est limité par la constitution",
    "A tax charged to Chinese immigrants to Canada": "Une taxe imposée aux immigrants chinois au Canada",
    "A women's rights activist": "Une militante pour les droits des femmes",
    "Aboriginal, French, British": "Autochtones, Français, Britanniques",
    "Aerospace, information technology, biotechnology": "Aérospatiale, technologies de l'information, biotechnologie",
    "All individuals have equal rights and opportunities": "Tous les individus ont des droits et des chances égaux",
    "At least every 5 years": "Au moins tous les 5 ans",
    "Both Charter and Official Languages Act": "La Charte et la Loi sur les langues officielles",
    "Both hockey and lacrosse": "Le hockey et la crosse",
    "British defeated French": "Les Britanniques ont vaincu les Français",
    "Canadian Broadcasting Corporation": "Société Radio-Canada",
    "Citizens 18 and older": "Citoyens de 18 ans et plus",
    "English and French": "Anglais et français",
    "English or French": "Anglais ou français",
    "Every 4 years": "Tous les 4 ans",
    "Every 5 years": "Tous les 5 ans",
    "Federal": "Fédéral",
    "French and English": "Français et anglais",
    "Hockey": "Hockey",
    "Lacrosse": "Crosse",
    "Maple Leaf": "Feuille d'érable",
    "NATO": "OTAN",
    "North American Free Trade Agreement": "Accord de libre-échange nord-américain",
    "Parks Canada": "Parcs Canada",
    "Rideau Hall": "Rideau Hall",
    "Royal Canadian Mounted Police": "Gendarmerie royale du Canada",
    "The King or Queen": "Le roi ou la reine",
    "The Prime Minister": "Le premier ministre",
    "USMCA": "ACEUM",
    "Yes": "Oui",
    "No": "Non",
    "True": "Vrai",
    "False": "Faux",
    "Alberta": "Alberta",
    "British Columbia": "Colombie-Britannique",
    "Manitoba": "Manitoba",
    "New Brunswick": "Nouveau-Brunswick",
    "Newfoundland and Labrador": "Terre-Neuve-et-Labrador",
    "Northwest Territories": "Territoires du Nord-Ouest",
    "Nova Scotia": "Nouvelle-Écosse",
    "Nunavut": "Nunavut",
    "Ontario": "Ontario",
    "Prince Edward Island": "Île-du-Prince-Édouard",
    "Quebec": "Québec",
    "Saskatchewan": "Saskatchewan",
    "Yukon": "Yukon",
    "Ottawa": "Ottawa",
    "Toronto": "Toronto",
    "Quebec City": "Québec",
    "Montreal": "Montréal",
    "Vancouver": "Vancouver",
    "Calgary": "Calgary",
    "Edmonton": "Edmonton",
    "Winnipeg": "Winnipeg",
    "Fredericton": "Fredericton",
    "St. John's": "Saint-Jean",
    "Halifax": "Halifax",
    "Charlottetown": "Charlottetown",
    "Regina": "Regina",
    "Whitehorse": "Whitehorse",
    "Yellowknife": "Yellowknife",
    "Iqaluit": "Iqaluit",
    "All territories": "Tous les territoires",
    "National defence, citizenship": "Défense nationale, citoyenneté",
    "Education, health care, natural resources": "Éducation, soins de santé, ressources naturelles",
    "Police, fire services": "Police, services d'incendie",
    "Postal service": "Service postal",
    "Beaver": "Castor",
    "Maple leaf": "Feuille d'érable",
    "O Canada": "Ô Canada",
    "July 1st": "1er juillet",
    "Red and white": "Rouge et blanc",
    "24 Sussex Drive": "24, promenade Sussex",
    "Parliament Hill": "Colline du Parlement",
    "Peace Tower": "Tour de la Paix",
    "Speech from the Throne": "Discours du Trône",
    "Comprehensive and Economic Trade Agreement": "Accord économique et commercial global",
    "Canada-European Union Comprehensive Economic and Trade Agreement": "Accord économique et commercial global Canada-Union européenne",
    "Comprehensive and Progressive Agreement for Trans-Pacific Partnership": "Accord de partenariat transpacifique global et progressiste",
    # --- bulk text options (so FR language shows all options in French) ---
    "A cultural event": "Un événement culturel",
    "A highway": "Une autoroute",
    "A leader of responsible government": "Un chef de gouvernement responsable",
    "A military court": "Un tribunal militaire",
    "A military event": "Un événement militaire",
    "A military government": "Un gouvernement militaire",
    "A military meeting": "Une réunion militaire",
    "A mining operation": "Une opération minière",
    "A mountain range": "Une chaîne de montagnes",
    "A municipal court": "Un tribunal municipal",
    "A provincial court": "Un tribunal provincial",
    "A river": "Une rivière",
    "A secret railway": "Un chemin de fer secret",
    "A system where the President has all power": "Un système où le président a tout le pouvoir",
    "A system where the monarch has unlimited power": "Un système où le monarque a un pouvoir illimité",
    "A system without elections": "Un système sans élections",
    "A tax on all immigrants": "Une taxe sur tous les immigrants",
    "A tax on exports": "Une taxe sur les exportations",
    "A tax on imports": "Une taxe sur les importations",
    "A trade dispute": "Un différend commercial",
    "A trade meeting": "Une réunion commerciale",
    "A transportation system": "Un système de transport",
    "A type of beaver": "Un type de castor",
    "A type of maple tree": "Un type d'érable",
    "A war hero": "Un héros de guerre",
    "A war with USA": "Une guerre avec les États-Unis",
    "Aboriginal, French, British, and other groups": "Autochtones, Français, Britanniques et autres groupes",
    "Act": "Loi",
    "Alaska Highway": "Route de l'Alaska",
    "Alexander Graham Bell": "Alexander Graham Bell",
    "Alexander Mackenzie": "Alexander Mackenzie",
    "Alice Munro": "Alice Munro",
    "All are the same": "Tous sont identiques",
    "All are the same size": "Tous ont la même taille",
    "All eastern provinces": "Toutes les provinces de l'Est",
    "All northern regions": "Toutes les régions du Nord",
    "All of them": "Tous",
    "All opposition parties": "Tous les partis d'opposition",
    "All power in one government": "Tout le pouvoir dans un seul gouvernement",
    "All provinces": "Toutes les provinces",
    "All provinces and territories": "Toutes les provinces et territoires",
    "All residents": "Tous les résidents",
    "Always Conservative": "Toujours conservateur",
    "Always Liberal": "Toujours libéral",
    "Always Parti Québécois": "Toujours Parti québécois",
    "Americans": "Américains",
    "Americans invaded": "Les Américains ont envahi",
    "An artist": "Un artiste",
    "An explorer": "Un explorateur",
    "Any language": "N'importe quelle langue",
    "Anyone with a SIN number": "Toute personne ayant un NAS",
    "Appalachian Mountains": "Appalaches",
    "Arctic Circle": "Cercle arctique",
    "Arctic territories": "Territoires arctiques",
    "Artists": "Artistes",
    "Atlantic Canada": "Canada atlantique",
    "Atlantic Region": "Région de l'Atlantique",
    "Atlantic Region, Central Canada, Prairie Region, West Coast, Northern Territories": "Région atlantique, Centre du Canada, Prairies, Côte Ouest, Territoires du Nord",
    "Atlantic, Central, Prairie, West Coast, North": "Atlantique, Centre, Prairies, Côte Ouest, Nord",
    "August 1": "1er août",
    "BC": "C.-B.",
    "BC, Alberta": "C.-B., Alberta",
    "Baker Lake": "Baker Lake",
    "Ballot numbers": "Numéros sur le bulletin",
    "Banff National Park": "Parc national Banff",
    "Beginning of Confederation": "Début de la Confédération",
    "Bill": "Projet de loi",
    "Blue and white": "Bleu et blanc",
    "Both La Fontaine and Baldwin": "La Fontaine et Baldwin",
    "Both Nobel Prize and Order of Canada": "Prix Nobel et Ordre du Canada",
    "Both Quebec and Ontario": "Québec et Ontario",
    "Both party and candidate names": "Noms du parti et du candidat",
    "Brandon": "Brandon",
    "Brian Mulroney": "Brian Mulroney",
    "British in 1763": "Britanniques en 1763",
    "Budget": "Budget",
    "C$": "C$",
    "CAD": "CAD",
    "CETA": "AECG",
    "CPTPP": "PTPGP",
    "Canada European Trade Alliance": "Alliance commerciale Canada-Europe",
    "Canada Pacific Trade Partnership Program": "Programme de partenariat commercial Canada-Pacifique",
    "Canada Parks": "Parcs Canada",
    "Canada the Beautiful": "Canada la belle",
    "Canada's greatest soldier": "Le plus grand soldat du Canada",
    "Canada, Mexico, UK": "Canada, Mexique, Royaume-Uni",
    "Canada, USA, Mexico": "Canada, États-Unis, Mexique",
    "Canada, USA, UK": "Canada, États-Unis, Royaume-Uni",
    "Canada-Greenland border": "Frontière Canada-Groenland",
    "Canada-Mexico border": "Frontière Canada-Mexique",
    "Canada-US border": "Frontière Canada-États-Unis",
    "Canadian Broadcasting Channel": "Chaîne de radiodiffusion canadienne",
    "Canadian Broadcasting Company": "Société Radio-Canada",
    "Canadian Business Corporation": "Société commerciale canadienne",
    "Canadian Dollar": "Dollar canadien",
    "Canadian Euro": "Euro canadien",
    "Canadian European Trade Agreement": "Accord commercial Canada-Europe",
    "Canadian Museum of History, Museum of Civilization, National Gallery": "Musée canadien de l'histoire, Musée de la civilisation, Musée des beaux-arts",
    "Canadian National Parks": "Parcs nationaux du Canada",
    "Canadian Pacific Trade Partnership": "Partenariat commercial Canada-Pacifique",
    "Canadian Peso": "Peso canadien",
    "Canadian Pound": "Livre canadienne",
    "Canadian Shield": "Bouclier canadien",
    "Canadian citizens": "Citoyens canadiens",
    "Canadian citizens 18 years or older": "Citoyens canadiens de 18 ans ou plus",
    "Canadians in 1867": "Canadiens en 1867",
    "Candidate names": "Noms des candidats",
    "Candidate names and party affiliations": "Noms des candidats et partis",
    "Caribou": "Caribou",
    "Central Canada": "Centre du Canada",
    "Central Canada, Prairie Region, North": "Centre du Canada, Prairies, Nord",
    "Central government": "Gouvernement central",
    "Charter of Rights and Freedoms": "Charte des droits et libertés",
    "Chief Justice": "Juge en chef",
    "Citizenship ceremony": "Cérémonie de citoyenneté",
    "Coalition government": "Gouvernement de coalition",
    "Coast Mountains": "Chaîne Côtière",
    "Committee review": "Examen en comité",
    "Comprehensive Economic and Trade Agreement": "Accord économique et commercial global",
    "Constitution only": "Constitution seulement",
    "Continental Economic Trade Agreement": "Accord commercial économique continental",
    "Continental Pacific Trade Partnership": "Partenariat commercial Pacifique continental",
    "Corner Brook": "Corner Brook",
    "Cornwall": "Cornwall",
    "Court of Appeal": "Cour d'appel",
    "Cured diabetes": "Diabète guéri",
    "Curling": "Curling",
    "Dartmouth": "Dartmouth",
    "David Thompson": "David Thompson",
    "Dawson City": "Dawson City",
    "December 11": "11 décembre",
    "December 31, 1867": "31 décembre 1867",
    "Democracy, Republic, Federalism": "Démocratie, République, Fédéralisme",
    "Diamonds, gold, zinc": "Diamants, or, zinc",
    "Dieppe": "Dieppe",
    "Division of power between federal and provincial governments": "Répartition des pouvoirs entre les gouvernements fédéral et provinciaux",
    "Drafting Confederation principles": "Rédaction des principes de la Confédération",
    "East, Central, West, North, South": "Est, Centre, Ouest, Nord, Sud",
    "East, West, North": "Est, Ouest, Nord",
    "East, West, North, South, Central": "Est, Ouest, Nord, Sud, Centre",
    "Education": "Éducation",
    "Elect representatives": "Élire des représentants",
    "Elected government": "Gouvernement élu",
    "End of Seven Years' War and cession of New France to Britain": "Fin de la guerre de Sept Ans et cession de la Nouvelle-France à la Grande-Bretagne",
    "End of World War I": "Fin de la Première Guerre mondiale",
    "End of a war": "Fin d'une guerre",
    "Enforce laws": "Appliquer les lois",
    "English only": "Anglais seulement",
    "English, French, and Indigenous languages": "Anglais, français et langues autochtones",
    "Equal pay for equal work": "À travail égal, salaire égal",
    "Established border in the east": "Frontière établie à l'est",
    "Established border in the west": "Frontière établie à l'ouest",
    "Every 3 years": "Tous les 3 ans",
    "Everyone is guilty until proven innocent": "Tous sont coupables jusqu'à preuve d'innocence",
    "Everyone is innocent until proven guilty": "Tous sont innocents jusqu'à preuve de culpabilité",
    "Existence of different cultures and ethnicities in a society": "Existence de différentes cultures et ethnies dans une société",
    "Explorers": "Explorateurs",
    "Famous Canadian artists": "Artistes canadiens célèbres",
    "Famous Canadian landscape painters": "Peintres paysagistes canadiens célèbres",
    "Famous Canadian thinkers and scholars": "Penseurs et universitaires canadiens célèbres",
    "Famous politicians": "Hommes politiques célèbres",
    "Federal Court": "Cour fédérale",
    "Federal government": "Gouvernement fédéral",
    "Federalism, Parliamentary democracy, Constitutional monarchy": "Fédéralisme, démocratie parlementaire, monarchie constitutionnelle",
    "First Confederation conference": "Première conférence de la Confédération",
    "First reading": "Première lecture",
    "Fishing": "Pêche",
    "Five": "Cinq",
    "Five Fathers of Confederation": "Cinq Pères de la Confédération",
    "Five explorers": "Cinq explorateurs",
    "Five large lakes between Canada and the United States": "Cinq grands lacs entre le Canada et les États-Unis",
    "Five military heroes": "Cinq héros militaires",
    "Five women who fought for women's right to vote": "Cinq femmes qui ont lutté pour le droit de vote des femmes",
    "Flag, Anthem": "Drapeau, Hymne",
    "Foreign policy": "Politique étrangère",
    "Forestry, energy, pulp and paper": "Foresterie, énergie, pâte et papier",
    "Fort Smith": "Fort Smith",
    "Four": "Quatre",
    "Fraser River": "Fleuve Fraser",
    "Frederick Banting and Charles Best": "Frederick Banting et Charles Best",
    "Freedom Tower": "Tour de la Liberté",
    "Freedom from taxes, Freedom from military service, Freedom from jury duty": "Exemption d'impôts, de service militaire, de jury",
    "Freedom from taxes, military service, jury duty": "Exemption d'impôts, service militaire, jury",
    "Freedom of conscience and religion, Freedom of thought, belief, opinion and expression, Freedom of peaceful assembly, Freedom of association": "Liberté de conscience et de religion, de pensée, de croyance, d'opinion et d'expression, de réunion pacifique, d'association",
    "Freedom of conscience and religion, thought, expression, peaceful assembly and association": "Liberté de conscience, religion, pensée, expression, réunion et association pacifiques",
    "Freedom of movement, work, education, health": "Liberté de mouvement, travail, éducation, santé",
    "Freedom of speech, press, religion, assembly": "Liberté d'expression, de presse, de religion, de réunion",
    "Freedom to work, Freedom to travel, Freedom to vote, Freedom to own property": "Liberté de travailler, de voyager, de voter, de posséder",
    "French defeated British": "Les Français ont vaincu les Britanniques",
    "French in 1763": "Français en 1763",
    "French only": "Français seulement",
    "French, British, American": "Français, Britannique, Américain",
    "Fruit orchards and vineyards": "Vergers et vignobles",
    "Full constitutional independence from Britain": "Indépendance constitutionnelle complète de la Grande-Bretagne",
    "Fur trade": "Commerce de la fourrure",
    "Fur trading": "Commerce de la fourrure",
    "GATT": "GATT",
    "Gabriel Dumont": "Gabriel Dumont",
    "Gander": "Gander",
    "Gatineau": "Gatineau",
    "General Andrew McNaughton": "Général Andrew McNaughton",
    "General Arthur Currie": "Général Arthur Currie",
    "General Guy Simonds": "Général Guy Simonds",
    "General Harry Crerar": "Général Harry Crerar",
    "General Sam Hughes": "Général Sam Hughes",
    "Getting a job, Taking care of one's family, Working hard": "Obtenir un emploi, Prendre soin de sa famille, Travailler dur",
    "God Save the Queen": "God Save the Queen",
    "God save the Queen, long live the King": "Que Dieu protège la Reine, longue vie au Roi",
    "Gold, lead, zinc": "Or, plomb, zinc",
    "Gold, silver, copper": "Or, argent, cuivre",
    "Government policy only": "Politique gouvernementale seulement",
    "Government responsible to the Queen": "Gouvernement responsable devant la Reine",
    "Government responsible to the people": "Gouvernement responsable devant le peuple",
    "Government responsible to the people through Parliament": "Gouvernement responsable devant le peuple par le Parlement",
    "Government that makes good decisions": "Gouvernement qui prend de bonnes décisions",
    "Government that must be accountable to Parliament": "Gouvernement qui doit rendre des comptes au Parlement",
    "Government with less than 50% of seats": "Gouvernement avec moins de 50 % des sièges",
    "Government with majority of seats": "Gouvernement avec majorité de sièges",
    "Government with many responsibilities": "Gouvernement avec de nombreuses responsabilités",
    "Governor General": "Gouverneur général",
    "Governor Simcoe": "Gouverneur Simcoe",
    "Great Bear Lake": "Grand lac de l'Ours",
    "Great Lakes": "Grands Lacs",
    "Great Slave Lake": "Grand lac des Esclaves",
    "Guglielmo Marconi": "Guglielmo Marconi",
    "Haines Junction": "Haines Junction",
    "Halifax, Fredericton, Charlottetown, St. John's": "Halifax, Fredericton, Charlottetown, Saint-Jean",
    "Halifax, St. John's": "Halifax, Saint-Jean",
    "Hamilton": "Hamilton",
    "Hay River": "Hay River",
    "Health care": "Soins de santé",
    "Henry Hudson": "Henry Hudson",
    "Highway 401": "Autoroute 401",
    "House, Senate, Courts": "Chambre, Sénat, Tribunaux",
    "Independence of Canada": "Indépendance du Canada",
    "Interpret and apply laws": "Interpréter et appliquer les lois",
    "Inuvik": "Inuvik",
    "It ended World War I": "Cela a mis fin à la Première Guerre mondiale",
    "It had no significance": "Cela n'avait pas d'importance",
    "It was Canada's first major victory as an independent nation": "Ce fut la première grande victoire du Canada en tant que nation indépendante",
    "It was a draw": "Ce fut un match nul",
    "It was the largest battle": "Ce fut la plus grande bataille",
    "It's always dark": "Il fait toujours noir",
    "It's very hot": "Il fait très chaud",
    "James Cook": "James Cook",
    "James Naismith": "James Naismith",
    "January 1, 1867": "1er janvier 1867",
    "January 11": "11 janvier",
    "Jasper National Park": "Parc national Jasper",
    "Jean Chrétien": "Jean Chrétien",
    "Jean Talon": "Jean Talon",
    "John A. Macdonald": "John A. Macdonald",
    "July 1": "1er juillet",
    "July 1, 1867": "1er juillet 1867",
    "July 4, 1867": "4 juillet 1867",
    "June 1": "1er juin",
    "Lake Athabasca": "Lac Athabasca",
    "Lake Winnipeg": "Lac Winnipeg",
    "Lakes in the Arctic": "Lacs dans l'Arctique",
    "Lakes in the Canadian Shield": "Lacs du Bouclier canadien",
    "Lakes in the Rocky Mountains": "Lacs dans les Rocheuses",
    "Largest strike in Canadian history": "Plus grande grève de l'histoire du Canada",
    "Laurentian Mountains": "Laurentides",
    "Laurentian Plateau": "Plateau laurentien",
    "Laval": "Laval",
    "Legal system based on judicial precedent": "Système juridique fondé sur la jurisprudence",
    "Legal system based on judicial precedent (in all provinces except Quebec)": "Système juridique fondé sur la jurisprudence (dans toutes les provinces sauf le Québec)",
    "Legal system based on written laws": "Système juridique fondé sur les lois écrites",
    "Legal system based on written laws (in Quebec)": "Système juridique fondé sur les lois écrites (au Québec)",
    "Legislation": "Législation",
    "Legislative process": "Processus législatif",
    "Lester B. Pearson": "Lester B. Pearson",
    "Lethbridge": "Lethbridge",
    "Lieutenant Governor": "Lieutenant-gouverneur",
    "London": "London",
    "Lord Durham": "Lord Durham",
    "Lord Elgin": "Lord Elgin",
    "Louis Riel": "Louis Riel",
    "Louis de Frontenac": "Louis de Frontenac",
    "Louis-Hippolyte La Fontaine": "Louis-Hippolyte La Fontaine",
    "Lucy Maud Montgomery": "Lucy Maud Montgomery",
    "Mackenzie River": "Fleuve Mackenzie",
    "Make laws": "Faire les lois",
    "Making laws": "Faire les lois",
    "Manitoba, Saskatchewan": "Manitoba, Saskatchewan",
    "Manitoba, Saskatchewan, Alberta": "Manitoba, Saskatchewan, Alberta",
    "Maple leaf, Beaver": "Feuille d'érable, Castor",
    "Maple leaf, Flag": "Feuille d'érable, Drapeau",
    "Margaret Atwood": "Margaret Atwood",
    "Maritime provinces only": "Provinces maritimes seulement",
    "Maritime, Central, Prairie, Pacific, Arctic": "Maritime, Centre, Prairies, Pacifique, Arctique",
    "Maritime, Ontario, Quebec, Prairies, BC": "Maritime, Ontario, Québec, Prairies, C.-B.",
    "Marshall McLuhan": "Marshall McLuhan",
    "Mayor": "Maire",
    "Men and women are equal under the law": "Les hommes et les femmes sont égaux devant la loi",
    "Michigan, Erie, Ontario, Superior, Great Bear": "Michigan, Érié, Ontario, Supérieur, Grand lac de l'Ours",
    "Military law": "Droit militaire",
    "Military rule": "Régime militaire",
    "Mining": "Exploitation minière",
    "Mining, manufacturing, technology": "Mines, fabrication, technologie",
    "Monarchy, Dictatorship, Federalism": "Monarchie, Dictature, Fédéralisme",
    "Moncton": "Moncton",
    "Monetary policy": "Politique monétaire",
    "Moose": "Orignal",
    "Moose Jaw": "Moose Jaw",
    "More than 600,000": "Plus de 600 000",
    "Mount Fairweather": "Mont Fairweather",
    "Mount Logan": "Mont Logan",
    "Mount Pearl": "Mount Pearl",
    "Mount Robson": "Mont Robson",
    "Mount Waddington": "Mont Waddington",
    "Municipal": "Municipal",
    "National American Free Trade Agreement": "Accord de libre-échange nord-américain",
    "National Gallery": "Musée des beaux-arts du Canada",
    "National Parks Service": "Service des parcs nationaux",
    "National defence, foreign policy, citizenship": "Défense nationale, politique étrangère, citoyenneté",
    "National government": "Gouvernement national",
    "Natural resources": "Ressources naturelles",
    "Naturalization ceremony": "Cérémonie de naturalisation",
    "New American Free Trade Agreement": "Nouvel accord de libre-échange nord-américain",
    "Nikola Tesla": "Nikola Tesla",
    "No award": "Aucun prix",
    "No cultures": "Aucune culture",
    "No equality": "Pas d'égalité",
    "No government": "Aucun gouvernement",
    "No languages": "Aucune langue",
    "No legal system": "Aucun système juridique",
    "No national museums": "Aucun musée national",
    "No such rights exist": "Ces droits n'existent pas",
    "No, never": "Non, jamais",
    "No, voting is secret": "Non, le vote est secret",
    "Nobel Prize in Medicine": "Prix Nobel de médecine",
    "None": "Aucun",
    "None of them": "Aucun d'entre eux",
    "North Atlantic Free Trade Agreement": "Accord de libre-échange nord-atlantique",
    "Northern Canada": "Nord du Canada",
    "Northern Territories": "Territoires du Nord",
    "Not yet": "Pas encore",
    "Nova Scotia (Halifax), New Brunswick (Fredericton), PEI (Charlottetown), Newfoundland and Labrador (St. John's)": "Nouvelle-Écosse (Halifax), Nouveau-Brunswick (Fredericton), Î.-P.-É. (Charlottetown), T.-N.-L. (Saint-Jean)",
    "Nova Scotia, New Brunswick, PEI, Newfoundland and Labrador": "Nouvelle-Écosse, Nouveau-Brunswick, Î.-P.-É., Terre-Neuve-et-Labrador",
    "Nova Scotia, New Brunswick, Prince Edward Island, Newfoundland and Labrador": "Nouvelle-Écosse, Nouveau-Brunswick, Île-du-Prince-Édouard, Terre-Neuve-et-Labrador",
    "Nova Scotia, PEI": "Nouvelle-Écosse, Î.-P.-É.",
    "November 1": "1er novembre",
    "November 11": "11 novembre",
    "O Canada! Our home and native land! True patriot love in all of us command": "Ô Canada! Notre pays et notre patrie! L'amour patriotique nous anime",
    "O Canada, land of the free, home of the brave": "Ô Canada, pays de la liberté, foyer des braves",
    "Oath ceremony": "Cérémonie du serment",
    "Obeying laws, Respecting others": "Respecter les lois, Respecter les autres",
    "Obeying the law": "Respecter la loi",
    "Official Languages Act": "Loi sur les langues officielles",
    "Oil and gas": "Pétrole et gaz",
    "Oil production": "Production pétrolière",
    "Oil, gas, coal": "Pétrole, gaz, charbon",
    "One": "Un",
    "Only Aboriginal peoples": "Seulement les peuples autochtones",
    "Only Nova Scotia and New Brunswick": "Seulement Nouvelle-Écosse et Nouveau-Brunswick",
    "Only Yukon and NWT": "Seulement Yukon et T.N.-O.",
    "Only as observer": "Seulement comme observateur",
    "Only candidate names": "Noms des candidats seulement",
    "Only for citizens": "Seulement pour les citoyens",
    "Only for some people": "Seulement pour certaines personnes",
    "Only in 1995": "Seulement en 1995",
    "Only in writing": "Seulement par écrit",
    "Only numbers": "Chiffres seulement",
    "Only one culture": "Une seule culture",
    "Only one museum": "Un seul musée",
    "Only provincial museums": "Musées provinciaux seulement",
    "Only through a lawyer": "Seulement par un avocat",
    "Only to family": "Seulement à la famille",
    "Only to officials": "Seulement aux responsables",
    "Ontario only": "Ontario seulement",
    "Ontario, Quebec": "Ontario, Québec",
    "Ontario, Quebec, Territories": "Ontario, Québec, Territoires",
    "Opening Address": "Discours d'ouverture",
    "Ottawa River": "Rivière des Outaouais",
    "Over 1000": "Plus de 1000",
    "Over 1500": "Plus de 1500",
    "Over 35,000": "Plus de 35 000",
    "Over 40,000": "Plus de 40 000",
    "Over 45,000": "Plus de 45 000",
    "Over 50": "Plus de 50",
    "Over 50,000": "Plus de 50 000",
    "Over 500": "Plus de 500",
    "Over 60": "Plus de 60",
    "Over 60,000": "Plus de 60 000",
    "Over 70": "Plus de 70",
    "Over 70,000": "Plus de 70 000",
    "Over 750": "Plus de 750",
    "Over 80": "Plus de 80",
    "Parliament": "Parlement",
    "Parliamentary process": "Processus parlementaire",
    "Party names": "Noms des partis",
    "Party names only": "Noms des partis seulement",
    "Paying taxes, Voting, Serving on jury": "Payer des impôts, Voter, Siéger à un jury",
    "People over 54": "Personnes de plus de 54 ans",
    "People over 54 and under 18": "Personnes de plus de 54 ans et de moins de 18 ans",
    "People over 55": "Personnes de plus de 55 ans",
    "People over 55 and under 18": "Personnes de plus de 55 ans et de moins de 18 ans",
    "People over 60 and under 16": "Personnes de plus de 60 ans et de moins de 16 ans",
    "People over 65": "Personnes de plus de 65 ans",
    "People over 65 and under 18": "Personnes de plus de 65 ans et de moins de 18 ans",
    "People under 18": "Personnes de moins de 18 ans",
    "Permanent residents": "Résidents permanents",
    "Pierre Elliott Trudeau": "Pierre Elliott Trudeau",
    "Pioneers in communication theory": "Pionniers de la théorie de la communication",
    "Polar Bear": "Ours polaire",
    "Police, fire services, libraries": "Police, pompiers, bibliothèques",
    "Politicians": "Hommes politiques",
    "Potatoes and Anne of Green Gables": "Pommes de terre et Anne... la maison aux pignons verts",
    "Prairie": "Prairie",
    "Prairie Provinces": "Provinces des Prairies",
    "Prairie Region": "Région des Prairies",
    "Premier": "Premier ministre (provincial)",
    "Prime Minister": "Premier ministre",
    "Prime Minister, Parliament, Supreme Court": "Premier ministre, Parlement, Cour suprême",
    "Prime Minister, Premier, Mayor": "Premier ministre, Premier, Maire",
    "Prince Albert": "Prince Albert",
    "Provincial": "Provincial",
    "Provincial Court": "Tribunal provincial",
    "Quebec Act of 1774": "Acte de Québec de 1774",
    "Quebec only": "Québec seulement",
    "Quebec, Ontario": "Québec, Ontario",
    "Rankin Inlet": "Rankin Inlet",
    "Recognition and respect for different cultures": "Reconnaissance et respect des différentes cultures",
    "Red Deer": "Red Deer",
    "Red and gold": "Rouge et or",
    "Red, white, and blue": "Rouge, blanc et bleu",
    "Rick Hansen": "Rick Hansen",
    "Right to work anywhere": "Droit de travailler n'importe où",
    "Rights of each person as an individual": "Droits de chaque personne en tant qu'individu",
    "Rights of groups": "Droits des groupes",
    "Rights of groups such as Aboriginal peoples": "Droits des groupes comme les peuples autochtones",
    "Rights of individuals only": "Droits des individus seulement",
    "Rights of the government": "Droits du gouvernement",
    "Robert Baldwin": "Robert Baldwin",
    "Robertson Davies": "Robertson Davies",
    "Rocky Mountains": "Rocheuses",
    "Royal Address": "Discours royal",
    "Royal Assent": "Sanction royale",
    "Royal Canadian Maritime Police": "Police maritime royale du Canada",
    "Royal Canadian Military Police": "Police militaire royale du Canada",
    "Royal Canadian Municipal Police": "Police municipale royale du Canada",
    "Saint John": "Saint-Jean",
    "Same opportunities and responsibilities": "Mêmes chances et responsabilités",
    "Saskatoon": "Saskatoon",
    "Saved millions of lives worldwide": "A sauvé des millions de vies dans le monde",
    "September 1": "1er septembre",
    "Seven Fathers of Confederation": "Sept Pères de la Confédération",
    "Seven military heroes": "Sept héros militaires",
    "Seven provinces": "Sept provinces",
    "Seven territories": "Sept territoires",
    "Simon Fraser": "Simon Fraser",
    "Sir John A. Macdonald": "Sir John A. Macdonald",
    "Sir Louis-Hippolyte La Fontaine": "Sir Louis-Hippolyte La Fontaine",
    "Six": "Six",
    "Some people are presumed guilty": "Certaines personnes sont présumées coupables",
    "Some people have more rights": "Certaines personnes ont plus de droits",
    "St. Lawrence River": "Fleuve Saint-Laurent",
    "State of the Union": "État de l'Union",
    "Statute": "Loi",
    "Steinbach": "Steinbach",
    "Stratford": "Stratford",
    "Study in Canada": "Étudier au Canada",
    "Studying": "Étudier",
    "Summerside": "Summerside",
    "Superior, Huron, Erie, Ontario, Winnipeg": "Supérieur, Huron, Érié, Ontario, Winnipeg",
    "Superior, Huron, Michigan, Erie, Ontario": "Supérieur, Huron, Michigan, Érié, Ontario",
    "Supreme Court Building": "Édifice de la Cour suprême",
    "Supreme Court of Canada": "Cour suprême du Canada",
    "Swearing-in ceremony": "Cérémonie d'assermentation",
    "Sydney": "Sydney",
    "Taking responsibility for oneself and family": "Prendre ses responsabilités pour soi et sa famille",
    "Temporary government": "Gouvernement temporaire",
    "Terrorist crisis in Quebec": "Crise terroriste au Québec",
    "Terry Fox": "Terry Fox",
    "The Bill of Rights": "La Déclaration des droits",
    "The Breadbasket of Canada": "Le grenier du Canada",
    "The Charter of Rights and Freedoms": "La Charte des droits et libertés",
    "The Chief Justice": "Le juge en chef",
    "The Constitution": "La Constitution",
    "The Gateway": "La Porte",
    "The Governor General": "Le gouverneur général",
    "The Heartland": "Le Cœur",
    "The Keystone": "La Clé de voûte",
    "The Magna Carta": "La Magna Carta",
    "The Maple Leaf": "La feuille d'érable",
    "The Maple Leaf Forever": "The Maple Leaf Forever",
    "The Mayor": "Le maire",
    "The Premier": "Le premier ministre",
    "The Province of a Thousand Lakes": "La province des Mille Lacs",
    "The Red Ensign": "Le Red Ensign",
    "The Stars and Stripes": "La bannière étoilée",
    "The Union Jack": "L'Union Jack",
    "The beaver": "Le castor",
    "The border between Canada and USA from ocean to Great Lakes": "La frontière entre le Canada et les États-Unis de l'océan aux Grands Lacs",
    "The candidate's name": "Le nom du candidat",
    "The creation of Canadian Confederation": "La création de la Confédération canadienne",
    "The flag": "Le drapeau",
    "The governing party": "Le parti au pouvoir",
    "The highest court in Canada": "Le plus haut tribunal au Canada",
    "The independence of Canada": "L'indépendance du Canada",
    "The largest party": "Le plus grand parti",
    "The maple leaf": "La feuille d'érable",
    "The moose": "L'orignal",
    "The party chosen by the Governor General": "Le parti choisi par le gouverneur général",
    "The party chosen by the PM": "Le parti choisi par le PM",
    "The party name": "Le nom du parti",
    "The party with the most seats": "Le parti avec le plus de sièges",
    "The party with the most seats in the House of Commons": "Le parti avec le plus de sièges à la Chambre des communes",
    "The party with the most votes": "Le parti avec le plus de voix",
    "The party with the second most seats": "Le parti avec le deuxième plus de sièges",
    "The party with the second-largest number of seats in the House of Commons": "Le parti avec le deuxième plus grand nombre de sièges à la Chambre des communes",
    "The person elected in your riding": "La personne élue dans votre circonscription",
    "The sun doesn't set in summer": "Le soleil ne se couche pas en été",
    "There are many sunny days": "Il y a beaucoup de jours ensoleillés",
    "They are each other's largest trading partners": "Ils sont les plus grands partenaires commerciaux l'un de l'autre",
    "They cooperate on many issues": "Ils coopèrent sur de nombreuses questions",
    "They have the same government system": "Ils ont le même système gouvernemental",
    "They share the world's longest undefended border": "Ils partagent la plus longue frontière non défendue au monde",
    "Third reading": "Troisième lecture",
    "This changes with elections": "Cela change avec les élections",
    "This varies by location": "Cela varie selon l'endroit",
    "Thomas Edison": "Thomas Edison",
    "Thompson": "Thompson",
    "Three": "Trois",
    "Throne Speech": "Discours du Trône",
    "To be loyal to Canada": "Être loyal envers le Canada",
    "To elect representatives": "Élire des représentants",
    "To fulfil their duties as citizens": "S'acquitter de leurs devoirs de citoyens",
    "To implement and enforce laws (Prime Minister and Cabinet)": "Mettre en œuvre et appliquer les lois (Premier ministre et Cabinet)",
    "To interpret laws": "Interpréter les lois",
    "To lead the government": "Diriger le gouvernement",
    "To make laws": "Faire les lois",
    "To obey the law": "Respecter la loi",
    "To represent the Crown in Canada": "Représenter la Couronne au Canada",
    "Tommy Douglas": "Tommy Douglas",
    "Toronto, Montreal, Vancouver": "Toronto, Montréal, Vancouver",
    "Toronto, Quebec City": "Toronto, Québec",
    "Tourists": "Touristes",
    "Trans-Canada Highway": "Route transcanadienne",
    "Traveling": "Voyager",
    "Truro": "Truro",
    "Two": "Deux",
    "US-Mexico border": "Frontière États-Unis-Mexique",
    "USA, Mexico, UK": "États-Unis, Mexique, Royaume-Uni",
    "USMCA/CUSMA": "ACEUM",
    "Unity Tower": "Tour de l'Unité",
    "Uprisings in Upper and Lower Canada": "Soulèvements dans le Haut et le Bas-Canada",
    "Use of many languages": "Usage de nombreuses langues",
    "Use of one language": "Usage d'une langue",
    "Use of two languages (English and French)": "Usage de deux langues (anglais et français)",
    "Victoria": "Victoria",
    "Victoria, Edmonton": "Victoria, Edmonton",
    "Victory Tower": "Tour de la Victoire",
    "Visit Canada": "Visiter le Canada",
    "Volunteering": "Bénévolat",
    "Vote in federal elections": "Voter aux élections fédérales",
    "Voting in elections": "Voter aux élections",
    "War heroes": "Héros de guerre",
    "Waterton Lakes National Park": "Parc national des Lacs-Waterton",
    "Watson Lake": "Watson Lake",
    "Wayne Gretzky": "Wayne Gretzky",
    "West Coast": "Côte Ouest",
    "Western Canada": "Ouest du Canada",
    "Whitehorse, Yellowknife, Iqaluit": "Whitehorse, Yellowknife, Iqaluit",
    "Wilfrid Laurier": "Wilfrid Laurier",
    "William Lyon Mackenzie King": "William Lyon Mackenzie King",
    "Winnipeg, Regina": "Winnipeg, Regina",
    "Won Nobel Prize": "A remporté le prix Nobel",
    "Work in Canada": "Travailler au Canada",
    "Working": "Travailler",
    "Yellowhead Highway": "Route Yellowhead",
    "Yes, always": "Oui, toujours",
    "Yes, you have the right": "Oui, vous avez le droit",
    "Yoho National Park": "Parc national Yoho",
    "Yukon (Whitehorse), Northwest Territories (Yellowknife), Nunavut (Iqaluit)": "Yukon (Whitehorse), Territoires du Nord-Ouest (Yellowknife), Nunavut (Iqaluit)",
    "1 million": "1 million",
    "1.2 million": "1,2 million",
    "1975 and 1980": "1975 et 1980",
    "1980 and 1995": "1980 et 1995",
    "1995 and 2000": "1995 et 2000",
    "Arviat": "Arviat",
    "The White House": "La Maison Blanche",
    "To fulfill their duties as citizens": "S'acquitter de leurs devoirs de citoyens",
}

# Book excerpts (explanations) EN -> FR – so all users can use the page in their language
EXPL_EN_FR_EXTRA = {
    "English settlement began in 1497 when John Cabot explored Canada's east coast.":
        "La colonisation anglaise a commencé en 1497 lorsque John Cabot a exploré la côte est du Canada.",
    "John Cabot, Jacques Cartier, and Samuel de Champlain all played important roles in establishing the first European settlements in Canada.":
        "John Cabot, Jacques Cartier et Samuel de Champlain ont tous joué un rôle important dans l'établissement des premières colonies européennes au Canada.",
    "The British Parliament passed the Quebec Act of 1774, which allowed French Canadians to maintain their language, religion, and civil law.":
        "Le Parlement britannique a adopté l'Acte de Québec de 1774, qui permettait aux Canadiens français de conserver leur langue, leur religion et leur droit civil.",
    "The Constitutional Act of 1791 granted to the Canadas, for the first time, legislative assemblies elected by the people.":
        "L'Acte constitutionnel de 1791 a accordé aux Canadas, pour la première fois, des assemblées législatives élues par le peuple.",
    "Lieutenant Colonel John Graves Simcoe was the first Governor of Upper Canada (now Ontario).":
        "Le lieutenant-colonel John Graves Simcoe a été le premier gouverneur du Haut-Canada (aujourd'hui l'Ontario).",
    "The British Parliament abolished slavery throughout the Empire in 1833.":
        "Le Parlement britannique a aboli l'esclavage dans tout l'Empire en 1833.",
    "The Fathers of Confederation include Sir John A. Macdonald, George-Étienne Cartier, and George Brown, among others.":
        "Les Pères de la Confédération comprennent Sir John A. Macdonald, George-Étienne Cartier et George Brown, entre autres.",
    "The phrase 'A Mari Usque Ad Mare' (From sea to sea) embodied the vision for the Dominion of Canada.":
        "La phrase « A Mari Usque Ad Mare » (D'un océan à l'autre) incarnait la vision du Dominion du Canada.",
    "The Canadian Pacific Railway made it possible for immigrants to settle in Western Canada.":
        "Le chemin de fer du Canadien Pacifique a permis aux immigrants de s'établir dans l'Ouest canadien.",
    "In 2006, the House of Commons recognized that the Quebecois form a nation within a united Canada.":
        "En 2006, la Chambre des communes a reconnu que les Québécois forment une nation au sein d'un Canada uni.",
    "La Francophonie is an international organization of French-speaking nations.":
        "La Francophonie est une organisation internationale des pays francophones.",
    "Terry Fox is a Canadian national hero because he ran across Canada to raise money for cancer research, despite having lost a leg to cancer.":
        "Terry Fox est un héros national canadien car il a traversé le Canada à la course pour amasser des fonds pour la recherche sur le cancer, malgré avoir perdu une jambe à cause du cancer.",
    "John Buchan was the 15th Governor General of Canada and a famous writer.":
        "John Buchan a été le 15e gouverneur général du Canada et un écrivain célèbre.",
    "Marjorie Turner-Bailey was the first Black woman elected to the Nova Scotia legislature.":
        "Marjorie Turner-Bailey a été la première femme noire élue à l'Assemblée législative de la Nouvelle-Écosse.",
    "The Canadian Pacific Railway symbolized both economic development and national unity, connecting Canada from coast to coast.":
        "Le chemin de fer du Canadien Pacifique symbolisait à la fois le développement économique et l'unité nationale, reliant le Canada d'un océan à l'autre.",
    "On election day, you mark an X next to the name of your chosen candidate on the ballot.":
        "Le jour du scrutin, vous mettez un X à côté du nom du candidat de votre choix sur le bulletin de vote.",
    "Canadian citizens who are 18 years of age or older are entitled to vote in federal elections.":
        "Les citoyens canadiens âgés de 18 ans ou plus ont le droit de voter aux élections fédérales.",
    "In Canada, you are not obliged to tell other people how you voted. Voting is secret.":
        "Au Canada, vous n'êtes pas obligé de dire aux autres comment vous avez voté. Le vote est secret.",
    "After an election, the party with the most seats in the House of Commons usually forms the government.":
        "Après une élection, le parti qui compte le plus de sièges à la Chambre des communes forme généralement le gouvernement.",
    "A minority government is a government that has less than 50% of the seats in the House of Commons.":
        "Un gouvernement minoritaire est un gouvernement qui détient moins de 50 % des sièges à la Chambre des communes.",
    "An election ballot shows the candidate names and their party affiliations.":
        "Un bulletin de vote indique les noms des candidats et leur parti.",
    "The three levels of government in Canada are: federal, provincial (or territorial), and municipal (local).":
        "Les trois ordres de gouvernement au Canada sont : fédéral, provincial (ou territorial) et municipal (local).",
    "The courts interpret and apply the law. They do not make laws or enforce them.":
        "Les tribunaux interprètent et appliquent la loi. Ils ne font pas les lois ni ne les appliquent de force.",
    "In Canada, you are allowed to question the police about their service or conduct.":
        "Au Canada, vous avez le droit de questionner la police sur son service ou sa conduite.",
    "The federal government is responsible for national defence, foreign policy, citizenship, and other matters of national concern.":
        "Le gouvernement fédéral est responsable de la défense nationale, de la politique étrangère, de la citoyenneté et d'autres questions d'intérêt national.",
    "Provincial governments are responsible for education, health care, natural resources, and other matters within their provinces.":
        "Les gouvernements provinciaux sont responsables de l'éducation, des soins de santé, des ressources naturelles et d'autres questions dans leurs provinces.",
    "The Governor General, on the advice of the Prime Minister, appoints the judges of the Supreme Court of Canada.":
        "Le gouverneur général, sur avis du premier ministre, nomme les juges de la Cour suprême du Canada.",
    "A law before it is passed is called a bill.":
        "Une loi avant d'être adoptée s'appelle un projet de loi.",
    "The final step before a bill becomes a law is Royal Assent, given by the Governor General or the monarch.":
        "La dernière étape avant qu'un projet de loi ne devienne une loi est la sanction royale, donnée par le gouverneur général ou le monarque.",
    "Responsible government means that the government is responsible to the people through Parliament.":
        "Le gouvernement responsable signifie que le gouvernement est responsable devant le peuple par l'intermédiaire du Parlement.",
    "Canada's system of government has three key characteristics: federalism, parliamentary democracy, and constitutional monarchy.":
        "Le système de gouvernement du Canada a trois caractéristiques clés : le fédéralisme, la démocratie parlementaire et la monarchie constitutionnelle.",
    "Canada has five distinct regions: Atlantic Region, Central Canada, Prairie Region, West Coast, and North.":
        "Le Canada compte cinq régions distinctes : la région de l'Atlantique, le Centre du Canada, les Prairies, la côte Ouest et le Nord.",
    "The Northern Territories cover more than one-third of Canada's land mass.":
        "Les territoires du Nord couvrent plus d'un tiers de la masse terrestre du Canada.",
    "The Rocky Mountains are located between Alberta and British Columbia.":
        "Les Rocheuses sont situées entre l'Alberta et la Colombie-Britannique.",
    "The Prairie Region includes the provinces of Manitoba, Saskatchewan, and Alberta.":
        "La région des Prairies comprend les provinces du Manitoba, de la Saskatchewan et de l'Alberta.",
    "The St. Lawrence River is the major river in Central Canada.":
        "Le fleuve Saint-Laurent est le principal cours d'eau du Centre du Canada.",
    "The Canadian Shield is a mineral-rich rock formation in the northern part of Central Canada.":
        "Le Bouclier canadien est une formation rocheuse riche en minéraux dans la partie nord du Centre du Canada.",
    "Yukon is the only Canadian territory that shares a border with another country (the United States).":
        "Le Yukon est le seul territoire canadien qui partage une frontière avec un autre pays (les États-Unis).",
    "The Atlantic Provinces are Nova Scotia, New Brunswick, Prince Edward Island, and Newfoundland and Labrador.":
        "Les provinces de l'Atlantique sont la Nouvelle-Écosse, le Nouveau-Brunswick, l'Île-du-Prince-Édouard et Terre-Neuve-et-Labrador.",
    "The Atlantic Region provinces and their capitals are: Nova Scotia (Halifax), New Brunswick (Fredericton), Prince Edward Island (Charlottetown), and Newfoundland and Labrador (St. John's).":
        "Les provinces de la région de l'Atlantique et leurs capitales sont : Nouvelle-Écosse (Halifax), Nouveau-Brunswick (Fredericton), Île-du-Prince-Édouard (Charlottetown) et Terre-Neuve-et-Labrador (Saint-Jean).",
    "The territories and their capitals are: Yukon (Whitehorse), Northwest Territories (Yellowknife), and Nunavut (Iqaluit).":
        "Les territoires et leurs capitales sont : Yukon (Whitehorse), Territoires du Nord-Ouest (Yellowknife) et Nunavut (Iqaluit).",
    "Central Canada is known as the industrial and manufacturing heartland of Canada.":
        "Le Centre du Canada est connu comme le cœur industriel et manufacturier du Canada.",
    "The Atlantic Region includes Nova Scotia, New Brunswick, Prince Edward Island, and Newfoundland and Labrador.":
        "La région de l'Atlantique comprend la Nouvelle-Écosse, le Nouveau-Brunswick, l'Île-du-Prince-Édouard et Terre-Neuve-et-Labrador.",
    "Ottawa is the capital of Canada.":
        "Ottawa est la capitale du Canada.",
    "Quebec has the most bilingual Canadians.":
        "Le Québec compte le plus de Canadiens bilingues.",
    "Saskatchewan is one of the most productive agricultural regions in the world.":
        "La Saskatchewan est l'une des régions agricoles les plus productives au monde.",
    "The Okanagan Valley is famous for its fruit orchards and vineyards.":
        "La vallée de l'Okanagan est célèbre pour ses vergers et ses vignobles.",
    "The majority of Métis people live in the Prairie Provinces.":
        "La majorité des Métis vivent dans les provinces des Prairies.",
    "The North is sometimes called the 'Land of the Midnight Sun' because the sun doesn't set in summer.":
        "Le Nord est parfois appelé « pays du soleil de minuit » car le soleil ne se couche pas en été.",
    "Diamonds, gold, and zinc are still mined in the territories today.":
        "Les diamants, l'or et le zinc sont encore extraits dans les territoires aujourd'hui.",
    "The five regions of Canada are Atlantic Region, Central Canada, Prairie Region, West Coast, and North.":
        "Les cinq régions du Canada sont la région de l'Atlantique, le Centre du Canada, les Prairies, la côte Ouest et le Nord.",
    "The British North America Act came into effect on July 1, 1867, creating the Dominion of Canada.":
        "L'Acte de l'Amérique du Nord britannique est entré en vigueur le 1er juillet 1867, créant le Dominion du Canada.",
    "Canada Day is celebrated on July 1st, the anniversary of Confederation.":
        "La fête du Canada est célébrée le 1er juillet, anniversaire de la Confédération.",
    "At the Battle of the Plains of Abraham in 1759, the British defeated the French forces, leading to British control of New France.":
        "Lors de la bataille des plaines d'Abraham en 1759, les Britanniques ont vaincu les forces françaises, conduisant au contrôle britannique de la Nouvelle-France.",
    "Sir Louis-Hippolyte La Fontaine was a leader of responsible government in Canada.":
        "Sir Louis-Hippolyte La Fontaine était un chef du gouvernement responsable au Canada.",
    "The discovery of insulin by Sir Frederick Banting and Charles Best saved millions of lives worldwide and won the Nobel Prize.":
        "La découverte de l'insuline par Sir Frederick Banting et Charles Best a sauvé des millions de vies dans le monde et a remporté le prix Nobel.",
    "General Sir Arthur Currie was Canada's greatest soldier and led Canadian forces in the First World War.":
        "Le général Sir Arthur Currie était le plus grand soldat du Canada et a dirigé les forces canadiennes pendant la Première Guerre mondiale.",
    "More than 600,000 Canadians served in the First World War.":
        "Plus de 600 000 Canadiens ont servi pendant la Première Guerre mondiale.",
    "Remembrance Day is celebrated on November 11 to honour those who served and died in wars.":
        "Le jour du Souvenir est célébré le 11 novembre pour honorer ceux qui ont servi et sont morts pendant les guerres.",
    "Canada's first financial institution, the Bank of Montreal, was opened in 1817.":
        "La première institution financière du Canada, la Banque de Montréal, a été ouverte en 1817.",
    "John Cabot was the first person to draw a map of Canada's east coast in 1497.":
        "John Cabot a été la première personne à dessiner une carte de la côte est du Canada en 1497.",
    "In 1813, Government House and the Parliament Buildings were burned by American forces during the War of 1812, not accidentally.":
        "En 1813, la résidence du gouverneur et les édifices du Parlement ont été incendiés par les forces américaines pendant la guerre de 1812, et non par accident.",
    "The British renamed the colony 'Province of Quebec' in 1763 after the Treaty of Paris.":
        "Les Britanniques ont renommé la colonie « Province de Québec » en 1763 après le traité de Paris.",
    "The Underground Railroad was a network of secret routes and safe houses that helped slaves escape to freedom in Canada.":
        "Le chemin de fer clandestin était un réseau de routes secrètes et de maisons sûres qui ont aidé les esclaves à s'échapper vers la liberté au Canada.",
    "The British Parliament banned the purchase and sale of slaves in 1807.":
        "Le Parlement britannique a interdit l'achat et la vente d'esclaves en 1807.",
    "Louis-Hippolyte La Fontaine and Robert Baldwin were the first leaders of responsible government in Canada in 1849.":
        "Louis-Hippolyte La Fontaine et Robert Baldwin ont été les premiers chefs du gouvernement responsable au Canada en 1849.",
    "Lord Durham recommended merging Upper and Lower Canada and giving them responsible government.":
        "Lord Durham a recommandé de fusionner le Haut-Canada et le Bas-Canada et de leur accorder le gouvernement responsable.",
    "The Group of Seven were famous Canadian artists who painted the Canadian landscape in the early 20th century.":
        "Le Groupe des Sept était des artistes canadiens célèbres qui ont peint le paysage canadien au début du XXe siècle.",
    "Louis Riel is known as the 'Father of Manitoba' and was a defender of Métis rights.":
        "Louis Riel est connu comme le « père du Manitoba » et était un défenseur des droits des Métis.",
    "Marshall McLuhan and Harold Innis were famous Canadian thinkers and scholars who made important contributions to communication theory.":
        "Marshall McLuhan et Harold Innis étaient des penseurs et universitaires canadiens célèbres qui ont apporté d'importantes contributions à la théorie de la communication.",
    "Rick Hansen circled the globe in a wheelchair to raise funds for spinal cord research.":
        "Rick Hansen a fait le tour du monde en fauteuil roulant pour amasser des fonds pour la recherche sur la moelle épinière.",
    "Only Canadian citizens who are 18 years of age or older are entitled to vote in federal elections.":
        "Seuls les citoyens canadiens âgés de 18 ans ou plus ont le droit de voter aux élections fédérales.",
    "In Canada's justice system, everyone is innocent until proven guilty. This is called presumption of innocence.":
        "Dans le système de justice canadien, toute personne est présumée innocente jusqu'à preuve du contraire. C'est ce qu'on appelle la présomption d'innocence.",
    "On a federal election ballot, you mark an X next to the name of your chosen candidate.":
        "Sur un bulletin de vote fédéral, vous mettez un X à côté du nom du candidat de votre choix.",
    "The Official Opposition at the federal level is the party with the second most seats in the House of Commons.":
        "L'opposition officielle au niveau fédéral est le parti qui compte le deuxième plus grand nombre de sièges à la Chambre des communes.",
    "Your member of Parliament is the person elected in your riding (electoral district) to represent you in the House of Commons.":
        "Votre député est la personne élue dans votre circonscription pour vous représenter à la Chambre des communes.",
    "The Sovereign's representative in the provinces is called the Lieutenant Governor.":
        "Le représentant du souverain dans les provinces s'appelle le lieutenant-gouverneur.",
    "Municipal governments pass laws known as 'by-laws' to regulate local matters.":
        "Les gouvernements municipaux adoptent des lois appelées « règlements municipaux » pour réglementer les questions locales.",
    "People who are 55 years of age or older are exempt from the language requirement for Canadian citizenship.":
        "Les personnes âgées de 55 ans ou plus sont exemptées de l'exigence linguistique pour la citoyenneté canadienne.",
    "The founding peoples of Canada are Aboriginal peoples, French, and British.":
        "Les peuples fondateurs du Canada sont les peuples autochtones, les Français et les Britanniques.",
    "Quebec has the most bilingual Canadians, with French and English both widely spoken.":
        "Le Québec compte le plus de Canadiens bilingues, le français et l'anglais y étant tous deux largement parlés.",
}
