# -*- coding: utf-8 -*-
# Full French translations for all citizenship test questions (EN -> FR).
# Used by extract_441_questions.py so that when FR is selected, questions are fully in French.

QUESTIONS_EN_FR = {
    "Name one source of Canadian law.": "Nommez une source de la loi canadienne.",
    "What is 'Magna Carta'?": "Qu'est-ce que la Magna Carta?",
    "When was the Magna Carta signed?": "Quand la Magna Carta a-t-elle été signée?",
    "What does the Great Charter of Freedom include?": "Que comprend la Grande Charte des libertés?",
    "What is 'Habeas corpus'?": "Qu'est-ce que l'habeas corpus?",
    "When was the Constitution of Canada amended to include the Charter of Rights and Freedoms?": "Quand la Constitution du Canada a-t-elle été modifiée pour inclure la Charte des droits et libertés?",
    "Who proclaimed the amended Constitution of Canada in 1982?": "Qui a proclamé la Constitution du Canada modifiée en 1982?",
    "What are the two principles upon which Canada is founded?": "Quels sont les deux principes sur lesquels le Canada est fondé?",
    "With which words does the Canadian Charter of Rights and Freedoms begin?": "Par quels mots commence la Charte canadienne des droits et libertés?",
    "What are 'mobility rights'?": "Que sont les « droits à la mobilité »?",
    "Which three rights are included in the Canadian Charter of Rights and Freedoms?": "Quels trois droits sont inclus dans la Charte canadienne des droits et libertés?",
    "True or False: French and English do not have equal status in Parliament and throughout the government.": "Vrai ou faux : Le français et l'anglais n'ont pas un statut égal au Parlement et dans l'ensemble du gouvernement.",
    "Canadians work hard to respect:": "Les Canadiens s'efforcent de respecter :",
    "What is a fundamental characteristic of the Canadian heritage and identity?": "Quelle est une caractéristique fondamentale du patrimoine et de l'identité canadienne?",
    "What are three responsibilities of Canadian citizenship?": "Quelles sont trois responsabilités de la citoyenneté canadienne?",
    "When called to do so, serving on a jury is:": "Lorsqu'on est convoqué, siéger à un jury est :",
    "True or False: There is no compulsory military service in Canada.": "Vrai ou faux : Il n'y a pas de service militaire obligatoire au Canada.",
    "What is a noble way to contribute to Canada and an excellent career choice?": "Quelle est une façon noble de contribuer au Canada et un excellent choix de carrière?",
    "Name two key documents that contain our rights and freedoms.": "Nommez deux documents clés qui contiennent nos droits et libertés.",
    "Identify four (4) rights that Canadians enjoy.": "Identifiez quatre droits dont jouissent les Canadiens.",
    "What are the three main groups of Aboriginal peoples?": "Quels sont les trois principaux groupes de peuples autochtones?",
    "Who are the Métis?": "Qui sont les Métis?",
    "What does the word 'Inuit' mean?": "Que signifie le mot « Inuit »?",
    "When did English settlement begin in Canada?": "Quand la colonisation anglaise a-t-elle commencé au Canada?",
    "Who established the first European settlements?": "Qui a établi les premières colonies européennes?",
    "Who passed the Quebec Act of 1774?": "Qui a adopté l'Acte de Québec de 1774?",
    "Which Act granted to the Canadas, for the first time, legislative assemblies elected by the people?": "Quel acte a accordé aux Canadas, pour la première fois, des assemblées législatives élues par le peuple?",
    "Who was Lieutenant Colonel John Graves Simcoe?": "Qui était le lieutenant-colonel John Graves Simcoe?",
    "When did the British Parliament abolish slavery throughout the Empire?": "Quand le Parlement britannique a-t-il aboli l'esclavage dans tout l'Empire?",
    "Name 3 fathers of Confederation.": "Nommez 3 pères de la Confédération.",
    "Which phrase embodied the vision for the Dominion of Canada?": "Quelle phrase incarnait la vision du Dominion du Canada?",
    "What made it possible for immigrants to settle in Western Canada?": "Qu'est-ce qui a permis aux immigrants de s'établir dans l'Ouest canadien?",
    "When did the House of Commons recognize that the Quebecois form a nation within a united Canada?": "Quand la Chambre des communes a-t-elle reconnu que les Québécois forment une nation au sein d'un Canada uni?",
    "What is 'La Francophonie'?": "Qu'est-ce que la Francophonie?",
    "Why is Terry Fox a Canadian national hero?": "Pourquoi Terry Fox est-il un héros national canadien?",
    "Who was John Buchan?": "Qui était John Buchan?",
    "Who is Marjorie Turner-Bailey?": "Qui est Marjorie Turner-Bailey?",
    "What is the origin of Habeas corpus?": "Quelle est l'origine de l'habeas corpus?",
    "What does Confederation mean?": "Que signifie la Confédération?",
    "What did the Canadian Pacific Railway symbolize?": "Que symbolisait le chemin de fer du Canadien Pacifique?",
    "What does it mean to say that Canada is a constitutional monarchy?": "Que signifie le fait que le Canada soit une monarchie constitutionnelle?",
    "What are the three branches of government?": "Quelles sont les trois branches du gouvernement?",
    "What is the difference between the role of the Queen and that of the Prime Minister?": "Quelle est la différence entre le rôle de la Reine et celui du premier ministre?",
    "What is the highest honour that Canadians can receive?": "Quel est le plus grand honneur que les Canadiens peuvent recevoir?",
    "When you go to vote on election day, what do you do?": "Lorsque vous allez voter le jour du scrutin, que faites-vous?",
    "Who is entitled to vote in Canadian federal elections?": "Qui a le droit de voter aux élections fédérales canadiennes?",
    "True or False: In Canada, are you obliged to tell other people how you voted?": "Vrai ou faux : Au Canada, êtes-vous obligé de dire aux autres comment vous avez voté?",
    "After an election, which party forms the government?": "Après une élection, quel parti forme le gouvernement?",
    "What is a minority government?": "Qu'est-ce qu'un gouvernement minoritaire?",
    "What is written on an election ballot?": "Qu'est-ce qui est écrit sur un bulletin de vote?",
    "What are the three levels of government?": "Quels sont les trois ordres de gouvernement?",
    "What is the role of the courts in Canada?": "Quel est le rôle des tribunaux au Canada?",
    "True or False: In Canada, are you allowed to question the police about their service or conduct?": "Vrai ou faux : Au Canada, avez-vous le droit de questionner la police sur son service ou sa conduite?",
    "What are the responsibilities of the federal government?": "Quelles sont les responsabilités du gouvernement fédéral?",
    "Which of the following are the responsibilities of the provincial government?": "Lequel des éléments suivants relève des responsabilités du gouvernement provincial?",
    "Who appoints the judges of the Supreme Court of Canada?": "Qui nomme les juges de la Cour suprême du Canada?",
    "What do you call a law before it is passed?": "Comment appelle-t-on une loi avant son adoption?",
    "What is the final step before a bill becomes a law?": "Quelle est la dernière étape avant qu'un projet de loi ne devienne une loi?",
    "What is meant by the term 'responsible government'?": "Que signifie l'expression « gouvernement responsable »?",
    "What are the three key characteristics of Canada's system of government?": "Quelles sont les trois caractéristiques clés du système de gouvernement du Canada?",
    "Name the five regions of Canada.": "Nommez les cinq régions du Canada.",
    "Which region covers more than one-third of Canada?": "Quelle région couvre plus d'un tiers du Canada?",
    "The mountain range located between Alberta and British Columbia is called:": "La chaîne de montagnes située entre l'Alberta et la Colombie-Britannique s'appelle :",
    "What provinces are located in the Prairie Region?": "Quelles provinces se trouvent dans la région des Prairies?",
    "The St. Lawrence River is the major river in:": "Le fleuve Saint-Laurent est le principal cours d'eau du :",
    "The mineral rich rock formation in the northern part of Central Canada is called:": "La formation rocheuse riche en minéraux dans la partie nord du Centre du Canada s'appelle :",
    "The only Canadian territory which shares a border with another country is:": "Le seul territoire canadien qui partage une frontière avec un autre pays est :",
    "What provinces are referred to as the Atlantic Provinces?": "Quelles provinces sont appelées les provinces de l'Atlantique?",
    "The provinces of the Atlantic Region and their capital cities are:": "Les provinces de la région de l'Atlantique et leurs capitales sont :",
    "The territories and their capital cities are:": "Les territoires et leurs capitales sont :",
    "Which region is known as the industrial and manufacturing heartland of Canada?": "Quelle région est connue comme le cœur industriel et manufacturier du Canada?",
    "What provinces are located in the Atlantic Region?": "Quelles provinces se trouvent dans la région de l'Atlantique?",
    "What is the capital of Canada?": "Quelle est la capitale du Canada?",
    "Which province has the most bilingual Canadians?": "Quelle province compte le plus de Canadiens bilingues?",
    "Which province is one of the most productive agricultural regions in the world?": "Quelle province est l'une des régions agricoles les plus productives au monde?",
    "What is the Okanagan Valley famous for?": "Pour quoi la vallée de l'Okanagan est-elle célèbre?",
    "Where do the majority of Métis people live in Canada?": "Où vit la majorité des Métis au Canada?",
    "Why is the North sometimes called the 'Land of the Midnight Sun'?": "Pourquoi le Nord est-il parfois appelé le « pays du soleil de minuit »?",
    "Which three minerals are still mined in the territories today?": "Quels trois minéraux sont encore extraits dans les territoires aujourd'hui?",
    "The five regions of Canada are Atlantic Region, __________, __________, West Coast and __________.": "Les cinq régions du Canada sont la région de l'Atlantique, __________, __________, la côte Ouest et __________.",
    "When did Canada become a country?": "Quand le Canada est-il devenu un pays?",
    "When did the British North America Act come into effect?": "Quand l'Acte de l'Amérique du Nord britannique est-il entré en vigueur?",
    "When is Canada Day?": "Quand est la fête du Canada?",
    "What happened at the Battle of the Plains of Abraham?": "Que s'est-il passé lors de la bataille des plaines d'Abraham?",
    "Who was Sir Louis-Hippolyte La Fontaine?": "Qui était Sir Louis-Hippolyte La Fontaine?",
    "What is the significance of the discovery of insulin by Sir Frederick Banting and Charles Best?": "Quelle est l'importance de la découverte de l'insuline par Sir Frederick Banting et Charles Best?",
    "Who was General Sir Arthur Currie?": "Qui était le général Sir Arthur Currie?",
    "Approximately how many Canadians served in the First World War?": "Approximativement combien de Canadiens ont servi pendant la Première Guerre mondiale?",
    "When is Remembrance Day celebrated?": "Quand le jour du Souvenir est-il célébré?",
    "When was Canada's first financial institution opened?": "Quand la première institution financière du Canada a-t-elle été ouverte?",
    "Who was the first person to draw a map of Canada's east coast?": "Qui a été la première personne à dessiner une carte de la côte est du Canada?",
    "True or False: In 1813, Government House and the Parliament Buildings were accidentally burned.": "Vrai ou faux : En 1813, la résidence du gouverneur et les édifices du Parlement ont été accidentellement incendiés.",
    "Who renamed the colony 'Province of Quebec'?": "Qui a renommé la colonie « Province de Québec »?",
    "What was the Underground Railroad?": "Qu'est-ce que le chemin de fer clandestin?",
    "In which year did the British Parliament ban the purchase and sale of slaves?": "En quelle année le Parlement britannique a-t-il interdit l'achat et la vente d'esclaves?",
    "Who was the first leader of a responsible government in Canada in 1849?": "Qui a été le premier chef d'un gouvernement responsable au Canada en 1849?",
    "Who recommended merging Upper and Lower Canada and giving them responsible government?": "Qui a recommandé de fusionner le Haut-Canada et le Bas-Canada et de leur accorder le gouvernement responsable?",
    "Who were the 'Group of Seven' in Canadian history?": "Qui étaient le « Groupe des Sept » dans l'histoire du Canada?",
    "Who is known as the 'Father of Manitoba' and a defender of Métis rights?": "Qui est connu comme le « père du Manitoba » et un défenseur des droits des Métis?",
    "Marshall McLuhan and Harold Innis were:": "Marshall McLuhan et Harold Innis étaient :",
    "Name four (4) fundamental freedoms that Canadians enjoy.": "Nommez quatre libertés fondamentales dont jouissent les Canadiens.",
    "What is meant by the equality of women and men?": "Que signifie l'égalité des femmes et des hommes?",
    "What are some examples of taking responsibility for yourself and your family?": "Quels sont des exemples d'assumer ses responsabilités et celles de sa famille?",
    "True or False: No treaty or other rights or freedoms of Aboriginal peoples will be negatively affected by the rights granted by the Canadian Charter.": "Vrai ou faux : Aucun traité ni autre droit ou liberté des peuples autochtones ne sera affecté négativement par les droits accordés par la Charte canadienne.",
    "Which of the following responsibilities comes with becoming a Canadian citizen?": "Laquelle des responsabilités suivantes accompagne la citoyenneté canadienne?",
    "What is a great way to make acquaintances, create contacts, and learn useful skills?": "Quelle est une excellente façon de faire des connaissances, d'établir des contacts et d'acquérir des compétences utiles?",
    "What is Canada's most recognized and respected symbol?": "Quel est le symbole du Canada le plus reconnu et respecté?",
    "Name two Canadian symbols.": "Nommez deux symboles canadiens.",
    "What are the first two lines of Canada's national anthem?": "Quelles sont les deux premières lignes de l'hymne national du Canada?",
    "Which legal documents protect the rights of Canadians regarding official languages?": "Quels documents juridiques protègent les droits des Canadiens concernant les langues officielles?",
    "Who circled the globe in a wheelchair to raise funds for spinal cord research?": "Qui a fait le tour du monde en fauteuil roulant pour amasser des fonds pour la recherche sur la moelle épinière?",
    "Which of the following is a non-Canadian NOT allowed to do?": "Lequel des éléments suivants un non-Canadien n'est-il PAS autorisé à faire?",
    "In Canada's justice system what does presumption of innocence mean?": "Dans le système de justice canadien, que signifie la présomption d'innocence?",
    "What do you mark on a federal election ballot?": "Que marquez-vous sur un bulletin de vote fédéral?",
    "Which party is the Official Opposition at the federal level?": "Quel parti est l'opposition officielle au niveau fédéral?",
    "Who is your member of Parliament?": "Qui est votre député?",
    "What do you call the Sovereign's representative in the provinces?": "Comment appelle-t-on le représentant du souverain dans les provinces?",
    "Which level of government in Canada passes laws known as 'by-laws'?": "Quel ordre de gouvernement au Canada adopte des lois appelées « règlements municipaux »?",
    "Who is exempt from the language requirement for Canadian citizenship?": "Qui est exempté de l'exigence linguistique pour la citoyenneté canadienne?",
    "Who were the founding peoples of Canada?": "Qui étaient les peuples fondateurs du Canada?",
    "Which three industries are important to Quebec's economy today?": "Quelles sont les trois industries importantes pour l'économie du Québec aujourd'hui?",
    "Which political party is in power in Quebec?": "Quel parti politique est au pouvoir au Québec?",
    "When did the House of Commons recognize that the Quebecois form a nation within a united Canada?": "Quand la Chambre des communes a-t-elle reconnu que les Québécois forment une nation au sein d'un Canada uni?",
    "Which province has the most bilingual Canadians?": "Quelle province compte le plus de Canadiens bilingues?",
    "Who renamed the colony 'Province of Quebec'?": "Qui a renommé la colonie « Province de Québec »?",
    "What happened at the Battle of the Plains of Abraham?": "Que s'est-il passé lors de la bataille des plaines d'Abraham?",
    "Who passed the Quebec Act of 1774?": "Qui a adopté l'Acte de Québec de 1774?",
    "Which Act granted, for the first time in Canada, legislative assemblies elected by the people?": "Quel acte a accordé, pour la première fois au Canada, des assemblées législatives élues par le peuple?",
    "Who was Sir Louis-Hippolyte La Fontaine?": "Qui était Sir Louis-Hippolyte La Fontaine?",
    "Who recommended merging Upper and Lower Canada and giving them responsible government?": "Qui a recommandé de fusionner le Haut-Canada et le Bas-Canada et de leur accorder le gouvernement responsable?",
    "What does 'responsible government' mean?": "Que signifie le « gouvernement responsable »?",
    "When did English settlement begin in Canada?": "Quand la colonisation anglaise a-t-elle commencé au Canada?",
    "Who established the first European settlements?": "Qui a établi les premières colonies européennes?",
    "What is a fundamental characteristic of the Canadian heritage and identity?": "Quelle est une caractéristique fondamentale du patrimoine et de l'identité canadienne?",
    "Canadians work hard to respect:": "Les Canadiens s'efforcent de respecter :",
    "Which legal documents protect the rights of Canadians regarding official languages?": "Quels documents juridiques protègent les droits des Canadiens concernant les langues officielles?",
    "What are the three main groups of Aboriginal peoples?": "Quels sont les trois principaux groupes de peuples autochtones?",
    "Where do the majority of Métis people live in Canada?": "Où vit la majorité des Métis au Canada?",
    "Which industry did many early Canadian companies engage in?": "Dans quelle industrie de nombreuses premières entreprises canadiennes étaient-elles engagées?",
    "What made it possible for immigrants to settle in Western Canada?": "Qu'est-ce qui a permis aux immigrants de s'établir dans l'Ouest canadien?",
    "What did the Canadian Pacific Railway symbolize?": "Que symbolisait le chemin de fer du Canadien Pacifique?",
    "Which province is one of the most productive agricultural regions in the world?": "Quelle province est l'une des régions agricoles les plus productives au monde?",
    "What is the Okanagan Valley famous for?": "Pour quoi la vallée de l'Okanagan est-elle célèbre?",
    "When was Canada's first financial institution opened?": "Quand la première institution financière du Canada a-t-elle été ouverte?",
    "Which region is known as the industrial and manufacturing heartland of Canada?": "Quelle région est connue comme le cœur industriel et manufacturier du Canada?",
    "The mineral rich rock formation in the northern part of Central Canada is called:": "La formation rocheuse riche en minéraux dans la partie nord du Centre du Canada s'appelle :",
    "Which three minerals are still mined in the territories today?": "Quels trois minéraux sont encore extraits dans les territoires aujourd'hui?",
    "What is a great way to make acquaintances, create contacts, and learn useful skills?": "Quelle est une excellente façon de faire des connaissances, d'établir des contacts et d'acquérir des compétences utiles?",
    "What is a noble way to contribute to Canada and an excellent career choice?": "Quelle est une façon noble de contribuer au Canada et un excellent choix de carrière?",
    "What are the responsibilities of the federal government?": "Quelles sont les responsabilités du gouvernement fédéral?",
    "Which of the following are the responsibilities of the provincial government?": "Lequel des éléments suivants relève des responsabilités du gouvernement provincial?",
    "What is a minority government?": "Qu'est-ce qu'un gouvernement minoritaire?",
    "After an election, which party forms the government?": "Après une élection, quel parti forme le gouvernement?",
    "What is the role of the courts in Canada?": "Quel est le rôle des tribunaux au Canada?",
    "Who appoints the judges of the Supreme Court of Canada?": "Qui nomme les juges de la Cour suprême du Canada?",
    "What do you call a law before it is passed?": "Comment appelle-t-on une loi avant son adoption?",
    "What is the final step before a bill becomes a law?": "Quelle est la dernière étape avant qu'un projet de loi ne devienne une loi?",
    "What is the capital city of Ontario?": "Quelle est la capitale de l'Ontario?",
    "What is the capital city of British Columbia?": "Quelle est la capitale de la Colombie-Britannique?",
    "What is the capital city of Alberta?": "Quelle est la capitale de l'Alberta?",
    "What is the capital city of Manitoba?": "Quelle est la capitale du Manitoba?",
    "What is the capital city of Saskatchewan?": "Quelle est la capitale de la Saskatchewan?",
    "What is the capital city of Quebec?": "Quelle est la capitale du Québec?",
    "What is the capital city of New Brunswick?": "Quelle est la capitale du Nouveau-Brunswick?",
    "What is the capital city of Nova Scotia?": "Quelle est la capitale de la Nouvelle-Écosse?",
    "What is the capital city of Prince Edward Island?": "Quelle est la capitale de l'Île-du-Prince-Édouard?",
    "What is the capital city of Newfoundland and Labrador?": "Quelle est la capitale de Terre-Neuve-et-Labrador?",
    "What is the capital city of Yukon?": "Quelle est la capitale du Yukon?",
    "What is the capital city of Northwest Territories?": "Quelle est la capitale des Territoires du Nord-Ouest?",
    "What is the capital city of Nunavut?": "Quelle est la capitale du Nunavut?",
    "How many provinces does Canada have?": "Combien de provinces le Canada compte-t-il?",
    "How many territories does Canada have?": "Combien de territoires le Canada compte-t-il?",
    "What is the largest province in Canada by area?": "Quelle est la plus grande province du Canada par sa superficie?",
    "What is the smallest province in Canada?": "Quelle est la plus petite province du Canada?",
    "Which province is known as 'Canada's Ocean Playground'?": "Quelle province est connue comme « terrain de jeu océanique du Canada »?",
    "What is the national animal of Canada?": "Quel est l'animal national du Canada?",
    "What is the national sport of Canada?": "Quel est le sport national du Canada?",
    "Who is Canada's head of state?": "Qui est le chef d'État du Canada?",
    "Who is Canada's head of government?": "Qui est le chef du gouvernement du Canada?",
    "How many members are in the House of Commons?": "Combien de députés siègent à la Chambre des communes?",
    "How many senators are in the Senate?": "Combien de sénateurs siègent au Sénat?",
    "What is the minimum voting age in Canada?": "Quel est l'âge minimum pour voter au Canada?",
    "How often are federal elections held in Canada?": "À quelle fréquence les élections fédérales ont-elles lieu au Canada?",
    "What is the name of Canada's national anthem?": "Quel est le nom de l'hymne national du Canada?",
    "When was O Canada officially adopted as the national anthem?": "Quand Ô Canada a-t-il été officiellement adopté comme hymne national?",
    "What are the official languages of Canada?": "Quelles sont les langues officielles du Canada?",
    "Which province is officially bilingual?": "Quelle province est officiellement bilingue?",
    "What is the name of the document that contains Canada's fundamental rights and freedoms?": "Quel est le nom du document qui contient les droits et libertés fondamentaux du Canada?",
    "When was the Canadian Charter of Rights and Freedoms added to the Constitution?": "Quand la Charte canadienne des droits et libertés a-t-elle été ajoutée à la Constitution?",
    "What are the four fundamental freedoms guaranteed by the Charter?": "Quelles sont les quatre libertés fondamentales garanties par la Charte?",
    "What is the name of the highest court in Canada?": "Quel est le nom de la plus haute cour du Canada?",
    "How many judges sit on the Supreme Court of Canada?": "Combien de juges siègent à la Cour suprême du Canada?",
    "What is the role of the Governor General?": "Quel est le rôle du gouverneur général?",
    "Who appoints the Governor General?": "Qui nomme le gouverneur général?",
    "What is the name of the ceremony where new citizens take the oath?": "Quel est le nom de la cérémonie lors de laquelle les nouveaux citoyens prêtent serment?",
    "What do new citizens promise in the Oath of Citizenship?": "Que promettent les nouveaux citoyens dans le serment de citoyenneté?",
    "What is the minimum age to serve on a jury in Canada?": "Quel est l'âge minimum pour siéger à un jury au Canada?",
    "What is the name of the longest river in Canada?": "Quel est le nom du plus long fleuve du Canada?",
    "What is the name of the highest mountain in Canada?": "Quel est le nom de la plus haute montagne du Canada?",
    "What are the Great Lakes?": "Que sont les Grands Lacs?",
    "What is the name of the largest lake entirely within Canada?": "Quel est le nom du plus grand lac entièrement au Canada?",
    "What is the name of the longest highway in Canada?": "Quel est le nom de la plus longue route du Canada?",
    "What is the name of the national park system in Canada?": "Quel est le nom du réseau des parcs nationaux au Canada?",
    "What is the name of the first national park in Canada?": "Quel est le nom du premier parc national au Canada?",
    "What is the name of the longest undefended border in the world?": "Quel est le nom de la plus longue frontière non défendue au monde?",
    "What is the name of the currency used in Canada?": "Quel est le nom de la monnaie utilisée au Canada?",
    "What is the symbol for the Canadian dollar?": "Quel est le symbole du dollar canadien?",
    "What is the name of the Canadian flag?": "Quel est le nom du drapeau canadien?",
    "When was the current Canadian flag adopted?": "Quand le drapeau canadien actuel a-t-il été adopté?",
    "What colors are on the Canadian flag?": "Quelles couleurs figurent sur le drapeau canadien?",
    "What is the name of the official residence of the Prime Minister?": "Quel est le nom de la résidence officielle du premier ministre?",
    "What is the name of the official residence of the Governor General?": "Quel est le nom de la résidence officielle du gouverneur général?",
    "What is the name of the building where Parliament meets?": "Quel est le nom de l'édifice où siège le Parlement?",
    "What is the name of the tower on Parliament Hill?": "Quel est le nom de la tour sur la Colline du Parlement?",
    "What is the name of the ceremony that marks the opening of Parliament?": "Quel est le nom de la cérémonie qui marque l'ouverture du Parlement?",
    "What is the name of the document that outlines the government's plans?": "Quel est le nom du document qui décrit les plans du gouvernement?",
    "What is the name of the process by which a bill becomes a law?": "Quel est le nom du processus par lequel un projet de loi devient une loi?",
    "When was the Magna Carta (Great Charter of Freedoms) signed?": "Quand la Magna Carta (Grande Charte des libertés) a-t-elle été signée?",
    "Who has the right to enter and leave Canada freely?": "Qui a le droit d'entrer au Canada et d'en sortir librement?",
    # --- 141 missing questions (full FR) ---
    "Approximately how many Canadians served in World War I?": "Approximativement combien de Canadiens ont servi pendant la Première Guerre mondiale?",
    "Approximately how many Canadians served in World War II?": "Approximativement combien de Canadiens ont servi pendant la Deuxième Guerre mondiale?",
    "How many Canadians were killed in World War I?": "Combien de Canadiens ont été tués pendant la Première Guerre mondiale?",
    "How many Canadians were killed in World War II?": "Combien de Canadiens ont été tués pendant la Deuxième Guerre mondiale?",
    "How many Great Lakes are there?": "Combien y a-t-il de Grands Lacs?",
    "How many National Historic Sites are registered in Canada?": "Combien de lieux historiques nationaux sont inscrits au Canada?",
    "How many UNESCO World Heritage Sites are in Canada?": "Combien de sites du patrimoine mondial de l'UNESCO y a-t-il au Canada?",
    "How many countries are part of CPTPP?": "Combien de pays font partie du PTPGP?",
    "How many national sports does Canada have?": "Combien de sports nationaux le Canada a-t-il?",
    "How many official languages does Canada have?": "Combien de langues officielles le Canada a-t-il?",
    "How many original provinces were there in Confederation in 1867?": "Combien de provinces originales y avait-il lors de la Confédération en 1867?",
    "How many provinces and territories does Canada have?": "Combien de provinces et territoires le Canada a-t-il?",
    "How many questions are in the citizenship test?": "Combien de questions y a-t-il au test de citoyenneté?",
    "How many treaties exist between the Canadian government and First Nations?": "Combien de traités existent entre le gouvernement canadien et les Premières Nations?",
    "How often must federal elections be held in Canada?": "À quelle fréquence les élections fédérales doivent-elles avoir lieu au Canada?",
    "In Canada, are you allowed to question the police about their service or conduct?": "Au Canada, avez-vous le droit de questionner la police sur son service ou sa conduite?",
    "In Canada, are you obliged to tell other people how you voted?": "Au Canada, êtes-vous obligé de dire aux autres comment vous avez voté?",
    "In what year did Canada become a country?": "En quelle année le Canada est-il devenu un pays?",
    "In what year did Jacques Cartier arrive in Canada?": "En quelle année Jacques Cartier est-il arrivé au Canada?",
    "In what year did Samuel de Champlain found Quebec City?": "En quelle année Samuel de Champlain a-t-il fondé Québec?",
    "In what year was Canada's maple leaf flag adopted?": "En quelle année le drapeau canadien à la feuille d'érable a-t-il été adopté?",
    "In what year was insulin discovered?": "En quelle année l'insuline a-t-elle été découverte?",
    "In what year was the Battle of Vimy Ridge?": "En quelle année a eu lieu la bataille de la crête de Vimy?",
    "In what year was the Canadian Constitution patriated?": "En quelle année la Constitution canadienne a-t-elle été rapatriée?",
    "In what year was the Treaty of Paris signed, ending the Seven Years' War?": "En quelle année le traité de Paris a-t-il été signé, mettant fin à la guerre de Sept Ans?",
    "In which languages can the citizenship test be taken?": "Dans quelles langues peut-on passer le test de citoyenneté?",
    "Is Canada a member of G20?": "Le Canada est-il membre du G20?",
    "Is Canada a member of G7?": "Le Canada est-il membre du G7?",
    "Is Canada a member of La Francophonie?": "Le Canada est-il membre de la Francophonie?",
    "Is Canada a member of NATO?": "Le Canada est-il membre de l'OTAN?",
    "Is Canada a member of the Commonwealth?": "Le Canada est-il membre du Commonwealth?",
    "Is Canada a member of the United Nations?": "Le Canada est-il membre de l'Organisation des Nations Unies?",
    "Is jury duty a legal duty of citizenship?": "Siéger à un jury est-il un devoir juridique de la citoyenneté?",
    "Name the five Great Lakes.": "Nommez les cinq Grands Lacs.",
    "The St. Lawrence River flows through which provinces?": "Le fleuve Saint-Laurent traverse quelles provinces?",
    "What are collective rights?": "Que sont les droits collectifs?",
    "What are individual rights?": "Que sont les droits individuels?",
    "What are mobility rights?": "Que sont les droits à la mobilité?",
    "What are some of Canada's national museums?": "Quels sont quelques musées nationaux du Canada?",
    "What are the five regions of Canada?": "Quelles sont les cinq régions du Canada?",
    "What are the provinces of the Atlantic Region and their capital cities?": "Quelles sont les provinces de la région de l'Atlantique et leurs capitales?",
    "What are the territories of Canada and their capital cities?": "Quels sont les territoires du Canada et leurs capitales?",
    "What are the territories of Northern Canada and their capital cities?": "Quels sont les territoires du Nord canadien et leurs capitales?",
    "What are the three branches of government in Canada?": "Quelles sont les trois branches du gouvernement au Canada?",
    "What are the three levels of government in Canada?": "Quels sont les trois ordres de gouvernement au Canada?",
    "What did Frederick Banting and Charles Best win for discovering insulin?": "Qu'ont remporté Frederick Banting et Charles Best pour la découverte de l'insuline?",
    "What does CBC stand for?": "Que signifie CBC?",
    "What does CETA stand for?": "Que signifie AECG?",
    "What does CPTPP stand for?": "Que signifie PTPGP?",
    "What does NAFTA stand for?": "Que signifie ALENA?",
    "What does RCMP stand for?": "Que signifie GRC?",
    "What does equality mean in Canada?": "Que signifie l'égalité au Canada?",
    "What is Canadarm?": "Qu'est-ce que le Canadarm?",
    "What is Civil Law?": "Qu'est-ce que le droit civil?",
    "What is Common Law?": "Qu'est-ce que le common law?",
    "What is Prince Edward Island famous for?": "Pour quoi l'Île-du-Prince-Édouard est-elle célèbre?",
    "What is a constitutional monarchy?": "Qu'est-ce qu'une monarchie constitutionnelle?",
    "What is a jury?": "Qu'est-ce qu'un jury?",
    "What is a parliamentary democracy?": "Qu'est-ce qu'une démocratie parlementaire?",
    "What is bilingualism?": "Qu'est-ce que le bilinguisme?",
    "What is cultural diversity?": "Qu'est-ce que la diversité culturelle?",
    "What is federalism?": "Qu'est-ce que le fédéralisme?",
    "What is multiculturalism?": "Qu'est-ce que le multiculturalisme?",
    "What is responsible government?": "Qu'est-ce que le gouvernement responsable?",
    "What is the 49th Parallel?": "Qu'est-ce que le 49e parallèle?",
    "What is the Bank of Canada responsible for?": "De quoi la Banque du Canada est-elle responsable?",
    "What is the Supreme Court of Canada?": "Qu'est-ce que la Cour suprême du Canada?",
    "What is the capital of the province or territory that you live in?": "Quelle est la capitale de la province ou du territoire où vous habitez?",
    "What is the citizenship test duration?": "Quelle est la durée du test de citoyenneté?",
    "What is the government of all of Canada called?": "Comment s'appelle le gouvernement de tout le Canada?",
    "What is the minimum age to vote in Canada?": "Quel est l'âge minimum pour voter au Canada?",
    "What is the minimum score to pass the citizenship test?": "Quel est le score minimum pour réussir le test de citoyenneté?",
    "What is the name of the mineral-rich rock formation in the northern part of Central Canada?": "Quel est le nom de la formation rocheuse riche en minéraux dans le nord du Centre du Canada?",
    "What is the name of the mountain range located between Alberta and British Columbia?": "Quel est le nom de la chaîne de montagnes située entre l'Alberta et la Colombie-Britannique?",
    "What is the nickname for Manitoba?": "Quel est le surnom du Manitoba?",
    "What is the nickname for Saskatchewan?": "Quel est le surnom de la Saskatchewan?",
    "What is the role of the Executive branch?": "Quel est le rôle du pouvoir exécutif?",
    "What is written on a federal election ballot?": "Qu'est-ce qui est écrit sur un bulletin de vote fédéral?",
    "What replaced NAFTA in 2020?": "Qu'est-ce qui a remplacé l'ALENA en 2020?",
    "What three industries are important to Quebec's economy today?": "Quelles sont les trois industries importantes pour l'économie du Québec aujourd'hui?",
    "What was the British North America Act (1867)?": "Qu'est-ce que l'Acte de l'Amérique du Nord britannique (1867)?",
    "What was the Canada Act (1982)?": "Qu'est-ce que la Loi sur le Canada (1982)?",
    "What was the Charlottetown Conference (1864)?": "Qu'est-ce que la conférence de Charlottetown (1864)?",
    "What was the Head Tax?": "Qu'est-ce que la taxe d'entrée (Head Tax)?",
    "What was the October Crisis (1970)?": "Qu'est-ce que la crise d'octobre (1970)?",
    "What was the Oregon Treaty (1846)?": "Qu'est-ce que le traité de l'Oregon (1846)?",
    "What was the Quebec Conference (1864)?": "Qu'est-ce que la conférence de Québec (1864)?",
    "What was the Treaty of Ghent (1814)?": "Qu'est-ce que le traité de Gand (1814)?",
    "What was the Treaty of Paris (1763)?": "Qu'est-ce que le traité de Paris (1763)?",
    "What was the Winnipeg General Strike (1919)?": "Qu'est-ce que la grève générale de Winnipeg (1919)?",
    "What was the significance of the Battle of Vimy Ridge in 1917?": "Quelle a été l'importance de la bataille de la crête de Vimy en 1917?",
    "What were the Rebellions of 1837?": "Qu'étaient les rébellions de 1837?",
    "When is Canada Day celebrated?": "Quand la fête du Canada est-elle célébrée?",
    "When was NAFTA implemented?": "Quand l'ALENA a-t-elle été mise en œuvre?",
    "When was the Charter of Rights and Freedoms incorporated into the Canadian Constitution?": "Quand la Charte des droits et libertés a-t-elle été intégrée à la Constitution canadienne?",
    "When was the Multiculturalism Act passed?": "Quand la Loi sur le multiculturalisme a-t-elle été adoptée?",
    "When was the Official Languages Act passed?": "Quand la Loi sur les langues officielles a-t-elle été adoptée?",
    "When was the multiculturalism policy adopted?": "Quand la politique du multiculturalisme a-t-elle été adoptée?",
    "When were the Quebec independence referendums held?": "Quand les référendums sur l'indépendance du Québec ont-ils eu lieu?",
    "Which Canadian territory shares a border with another country?": "Quel territoire canadien partage une frontière avec un autre pays?",
    "Which Prime Minister served from 1968-1979 and 1980-1984?": "Quel premier ministre a été en fonction de 1968 à 1979 et de 1980 à 1984?",
    "Which Prime Minister won the Nobel Peace Prize?": "Quel premier ministre a remporté le prix Nobel de la paix?",
    "Which federal political party is His Majesty's Loyal Opposition?": "Quel parti politique fédéral est l'opposition officielle de Sa Majesté?",
    "Which industries did many early Canadian companies engage in?": "Dans quelles industries de nombreuses premières entreprises canadiennes étaient-elles engagées?",
    "Which is the smallest province in Canada?": "Quelle est la plus petite province du Canada?",
    "Which is the youngest province in Canada?": "Quelle est la plus jeune province du Canada?",
    "Which of the following are responsibilities of the provincial government?": "Lequel des éléments suivants relève des responsabilités du gouvernement provincial?",
    "Which of the following is NOT true about the Canada/USA relationship?": "Lequel des éléments suivants n'est PAS vrai concernant les relations Canada/États-Unis?",
    "Which province is famous for oil and gas industry and the Rocky Mountains?": "Quelle province est célèbre pour l'industrie pétrolière et gazière et les Rocheuses?",
    "Which province is known as the 'Breadbasket of Canada'?": "Quelle province est connue comme le « grenier du Canada »?",
    "Which province is known as the 'Province of a Thousand Lakes'?": "Quelle province est connue comme la « province aux mille lacs »?",
    "Which province is on the Pacific coast and known for mountains and nature?": "Quelle province est sur la côte du Pacifique et connue pour ses montagnes et sa nature?",
    "Which province is the most populous in Canada?": "Quelle province est la plus peuplée du Canada?",
    "Which province is the only one with French as the official language?": "Quelle province est la seule à avoir le français comme langue officielle?",
    "Which province joined Canada in 1949?": "Quelle province a rejoint le Canada en 1949?",
    "Which provinces are located in the Prairie Region?": "Quelles provinces se trouvent dans la région des Prairies?",
    "Which region covers more than one-third of Canada's land mass?": "Quelle région couvre plus d'un tiers de la masse terrestre du Canada?",
    "Which territory has diamonds, gold, and zinc mining?": "Quel territoire a des mines de diamants, d'or et de zinc?",
    "Which territory is the largest and youngest?": "Quel territoire est le plus grand et le plus jeune?",
    "Which territory is the smallest and westernmost?": "Quel territoire est le plus petit et le plus à l'ouest?",
    "Which territory was created in 1999?": "Quel territoire a été créé en 1999?",
    "Which three countries were part of NAFTA?": "Quels trois pays faisaient partie de l'ALENA?",
    "Who discovered insulin?": "Qui a découvert l'insuline?",
    "Who founded Quebec City?": "Qui a fondé Québec?",
    "Who invented the telephone (though patented in USA)?": "Qui a inventé le téléphone (breveté aux États-Unis)?",
    "Who is exempt from the citizenship test?": "Qui est exempté du test de citoyenneté?",
    "Who is known as the 'Father of Canadian Medicare'?": "Qui est connu comme le « père de l'assurance-maladie canadienne »?",
    "Who was Canada's first Prime Minister?": "Qui a été le premier premier ministre du Canada?",
    "Who was Canada's longest-serving Prime Minister?": "Qui a été le premier ministre du Canada ayant servi le plus longtemps?",
    "Who was David Thompson?": "Qui était David Thompson?",
    "Who was Nellie McClung?": "Qui était Nellie McClung?",
    "Who was the commander of Canadian forces in World War I?": "Qui était le commandant des forces canadiennes pendant la Première Guerre mondiale?",
    "Who was the commander of Canadian forces in World War II?": "Qui était le commandant des forces canadiennes pendant la Deuxième Guerre mondiale?",
    "Who was the first European to arrive in Canada?": "Qui a été le premier Européen à arriver au Canada?",
    "Who was the first European to reach the Pacific Ocean by land?": "Qui a été le premier Européen à atteindre l'océan Pacifique par la terre?",
    "Who was the first French-Canadian Prime Minister of Canada?": "Qui a été le premier premier ministre canadien-français du Canada?",
    "Who were Marshall McLuhan and Harold Innis?": "Qui étaient Marshall McLuhan et Harold Innis?",
    "Who were the 'Famous Five'?": "Qui étaient les « Célèbres cinq »?",
    "Who were the 'Group of Seven'?": "Qui étaient le « Groupe des Sept »?",
    "Who were the first leaders of a responsible government in Canada in 1849?": "Qui ont été les premiers chefs d'un gouvernement responsable au Canada en 1849?",
    "Who wrote 'Anne of Green Gables'?": "Qui a écrit « Anne... la maison aux pignons verts »?",
}
