# One-off generator — run: python scripts/_gen_chapter9_economy_json.py
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "static" / "chapter9_canada_economy_questions.json"

rows = [
    {
        "q": "In what year did Canada enact free trade with the United States?",
        "q_fa": "کانادا در چه سالی تجارت آزاد با ایالات متحده را به اجرا گذاشت؟",
        "q_fr": "En quelle année le Canada a-t-il mis en place le libre-échange avec les États-Unis?",
        "options": ["1979", "1892", "1988", "1998"],
        "options_fr": ["1979", "1892", "1988", "1998"],
        "options_fa": ["۱۹۷۹", "۱۸۹۲", "۱۹۸۸", "۱۹۹۸"],
        "correct": 2,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "The Canada–United States Free Trade Agreement (FTA) came into force in 1988.",
    },
    {
        "q": 'What does "NAFTA" mean?',
        "q_fa": "«NAFTA» به چه معناست؟",
        "q_fr": 'Que signifie « NAFTA »?',
        "options": [
            "North American Free Treasury Agreement",
            "North American Forced Trade Agreement",
            "National Armed Forces Treaty Agreement",
            "North American Free Trade Agreement",
        ],
        "options_fr": [
            "Accord nord-américain du trésor libre",
            "Accord nord-américain de commerce forcé",
            "Accord national des forces armées",
            "Accord de libre-échange nord-américain (ALENA)",
        ],
        "options_fa": [
            "قرارداد خزانه‌داری آزاد آمریکای شمالی",
            "قرارداد تجارت اجباری آمریکای شمالی",
            "معاهدهٔ نیروهای مسلح ملی",
            "قرارداد تجارت آزاد آمریکای شمالی",
        ],
        "correct": 3,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "NAFTA stands for the North American Free Trade Agreement.",
    },
    {
        "q": "What is the NAFTA agreement?",
        "q_fa": "قرارداد NAFTA چیست؟",
        "q_fr": "Qu'est-ce que l'accord de l'ALENA (NAFTA)?",
        "options": [
            "Free trade between Canada, the United States and Mexico",
            "Free trade between Canada, the United States and Europe",
            "Free trade between Canada, the United States and the United Kingdom",
            "Free trade between Canada, Europe and Mexico",
        ],
        "options_fr": [
            "Libre-échange entre le Canada, les États-Unis et le Mexique",
            "Libre-échange entre le Canada, les États-Unis et l'Europe",
            "Libre-échange entre le Canada, les États-Unis et le Royaume-Uni",
            "Libre-échange entre le Canada, l'Europe et le Mexique",
        ],
        "options_fa": [
            "تجارت آزاد میان کانادا، ایالات متحده و مکزیک",
            "تجارت آزاد میان کانادا، ایالات متحده و اروپا",
            "تجارت آزاد میان کانادا، ایالات متحده و بریتانیا",
            "تجارت آزاد میان کانادا، اروپا و مکزیک",
        ],
        "correct": 0,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "NAFTA created a free trade zone among Canada, the United States and Mexico.",
    },
    {
        "q": "Canada's economy is among the top:",
        "q_fa": "اقتصاد کانادا در میان چند اقتصاد بزرگ جهان قرار دارد؟",
        "q_fr": "L'économie du Canada se classe parmi les :",
        "options": ["5", "10", "20", "3"],
        "options_fr": ["5", "10", "20", "3"],
        "options_fa": ["۵", "۱۰", "۲۰", "۳"],
        "correct": 1,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "Canada has one of the world's largest economies (often cited among the top ten).",
    },
    {
        "q": "What are Canada's main types of industries?",
        "q_fa": "انواع اصلی صنایع کانادا کدامند؟",
        "q_fr": "Quels sont les principaux types d'industries au Canada?",
        "options": [
            "Service, manufacturing and natural resources",
            "Service, fishing and natural resources",
            "Tourism and natural resources",
            "Farming and fishing",
        ],
        "options_fr": [
            "Services, fabrication et ressources naturelles",
            "Services, pêche et ressources naturelles",
            "Tourisme et ressources naturelles",
            "Agriculture et pêche",
        ],
        "options_fa": [
            "خدمات، تولیدی و منابع طبیعی",
            "خدمات، ماهیگیری و منابع طبیعی",
            "گردشگری و منابع طبیعی",
            "کشاورزی و ماهیگیری",
        ],
        "correct": 0,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "Canada's economy includes service industries, manufacturing industries and natural resources industries.",
    },
    {
        "q": "In what area do Canadians mostly work nowadays?",
        "q_fa": "امروزه کانادایی‌ها عمدتاً در کدام بخش کار می‌کنند؟",
        "q_fr": "Dans quel secteur les Canadiens travaillent-ils surtout aujourd'hui?",
        "options": [
            "Manufacturing industries",
            "Natural resources industries",
            "Farming industries",
            "Service industries",
        ],
        "options_fr": [
            "Industries manufacturières",
            "Industries des ressources naturelles",
            "Industries agricoles",
            "Industries des services",
        ],
        "options_fa": [
            "صنایع تولیدی",
            "صنایع منابع طبیعی",
            "صنایع کشاورزی",
            "صنایع خدماتی",
        ],
        "correct": 3,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "The majority of working Canadians now have jobs in service industries.",
    },
    {
        "q": "Which industries have played an important part in Canada's story and development?",
        "q_fa": "کدام صنایع در داستان و پیشرفت کانادا نقش مهمی داشته‌اند؟",
        "q_fr": "Quelles industries ont joué un rôle important dans l'histoire et le développement du Canada?",
        "options": [
            "Manufacturing industries",
            "Service industries",
            "Natural resources industries",
            "Trading industries",
        ],
        "options_fr": [
            "Industries manufacturières",
            "Industries des services",
            "Industries des ressources naturelles",
            "Industries du commerce",
        ],
        "options_fa": [
            "صنایع تولیدی",
            "صنایع خدماتی",
            "صنایع منابع طبیعی",
            "صنایع تجاری",
        ],
        "correct": 2,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "Natural resources industries have been central to Canada's history and development.",
    },
    {
        "q": "Who is Canada's largest international trading partner?",
        "q_fa": "بزرگ‌ترین شریک تجاری بین‌المللی کانادا کیست؟",
        "q_fr": "Qui est le plus grand partenaire commercial international du Canada?",
        "options": ["United States", "Mexico", "Europe", "China"],
        "options_fr": ["États-Unis", "Mexique", "Europe", "Chine"],
        "options_fa": ["ایالات متحده", "مکزیک", "اروپا", "چین"],
        "correct": 0,
        "page": 43,
        "section": "Canada's Economy",
        "book_text": "The United States is Canada's largest trading partner.",
    },
    {
        "q": "How much of Canadian exports are destined for the U.S.A.?",
        "q_fa": "چه سهمی از صادرات کانادا به ایالات متحده می‌رود؟",
        "q_fr": "Quelle part des exportations canadiennes est destinée aux États-Unis?",
        "options": [
            "Two-thirds",
            "Over three-quarters",
            "Half",
            "Over one-third",
        ],
        "options_fr": [
            "Les deux tiers",
            "Plus des trois quarts",
            "La moitié",
            "Plus du tiers",
        ],
        "options_fa": [
            "دو سوم",
            "بیش از سه‌چهارم",
            "نیمی",
            "بیش از یک‌سوم",
        ],
        "correct": 1,
        "page": 43,
        "section": "Canada's Economy",
        "book_text": "A very large share of Canadian exports go to the United States (often over three-quarters in study materials).",
    },
    {
        "q": 'What is traditionally known as "the world\'s longest undefended border"?',
        "q_fa": "مرز بدون دفاع نظامی «طولانی‌ترین مرز بدون دفاع جهان» کدام است؟",
        "q_fr": 'Qu\'est-ce qui est traditionnellement appelé « la plus longue frontière non défendue du monde »?',
        "options": [
            "Both Canadian Atlantic and Pacific coasts",
            "Mexico–U.S.A. border",
            "Canada–U.S.A. border",
            "The Great Wall of China",
        ],
        "options_fr": [
            "Les côtes atlantique et pacifique du Canada",
            "Frontière Mexique–É.-U.",
            "Frontière Canada–É.-U.",
            "La Grande Muraille de Chine",
        ],
        "options_fa": [
            "هر دو ساحل اقیانوس اطلس و آرام کانادا",
            "مرز مکزیک و ایالات متحده",
            "مرز کانادا و ایالات متحده",
            "دیوار بزرگ چین",
        ],
        "correct": 2,
        "page": 43,
        "section": "Canada's Economy",
        "book_text": "The Canada–United States border is often described as the world's longest undefended border.",
    },
    {
        "q": "Which of the following statements is false about the Canada–U.S.A. relationship?",
        "q_fa": "کدام گزینه دربارهٔ روابط کانادا و ایالات متحده نادرست است؟",
        "q_fr": "Laquelle des affirmations suivantes est fausse concernant les relations Canada–É.-U.?",
        "options": [
            "They have the biggest bilateral trading relationship in the world",
            "Canada exports almost no goods to the U.S.A.",
            "They have the world's longest undefended border",
            "Millions of Canadians and Americans cross the Canada–U.S.A. border every year",
        ],
        "options_fr": [
            "Ils ont la plus grande relation commerciale bilatérale au monde",
            "Le Canada n'exporte presque aucune marchandise vers les É.-U.",
            "Ils ont la plus longue frontière non défendue au monde",
            "Des millions de Canadiens et d'Américains franchissent la frontière chaque année",
        ],
        "options_fa": [
            "بزرگ‌ترین روابط تجاری دوجانبهٔ جهان را دارند",
            "کانادا تقریباً هیچ کالایی به ایالات متحده صادر نمی‌کند",
            "طولانی‌ترین مرز بدون دفاع نظامی جهان را دارند",
            "هر سال میلیون‌ها کانادایی و آمریکایی از مرز عبور می‌کنند",
        ],
        "correct": 1,
        "page": 43,
        "section": "Canada's Economy",
        "book_text": "Canada and the United States are major trading partners; the claim that Canada exports almost no goods to the U.S. is false.",
    },
    {
        "q": "Which of the following symbolizes the close ties and common interests of Canada and the U.S.A.?",
        "q_fa": "کدام مورد پیوندهای نزدیک و منافع مشترک کانادا و ایالات متحده را نماد می‌کند؟",
        "q_fr": "Lequel des éléments suivants symbolise les liens étroits et les intérêts communs du Canada et des É.-U.?",
        "options": [
            "The Statue of Liberty",
            "The Stanley Cup",
            "The Peace Arch",
            "The Peace Tower",
        ],
        "options_fr": [
            "La Statue de la Liberté",
            "La Coupe Stanley",
            "L'Arche de la Paix",
            "La Tour de la Paix",
        ],
        "options_fa": [
            "مجسمهٔ آزادی",
            "جام استنلی",
            "طاق صلح (Peace Arch)",
            "برج صلح (Peace Tower)",
        ],
        "correct": 2,
        "page": 43,
        "section": "Canada's Economy",
        "book_text": "The Peace Arch at the Canada–U.S. border symbolizes peace and friendship between the two countries.",
    },
    {
        "q": "Which following countries are part of the G8?",
        "q_fa": "کدام کشورها عضو گروه G8 بوده‌اند (طبق مطالعهٔ رایج)؟",
        "q_fr": "Lesquels des pays suivants font partie du G8 (selon le guide d'étude classique)?",
        "options": [
            "United States, Germany, the United Kingdom, Italy, France, Canada, China and Russia",
            "United States, Germany, the United Kingdom, Japan, Canada, Russia, France and China",
            "United States, the United Kingdom, Japan, Canada, Australia, Russia, France and China",
            "United States, Germany, the United Kingdom, Italy, France, Japan, Canada and Russia",
        ],
        "options_fr": [
            "É.-U., Allemagne, R.-U., Italie, France, Canada, Chine et Russie",
            "É.-U., Allemagne, R.-U., Japon, Canada, Russie, France et Chine",
            "É.-U., R.-U., Japon, Canada, Australie, Russie, France et Chine",
            "É.-U., Allemagne, R.-U., Italie, France, Japon, Canada et Russie",
        ],
        "options_fa": [
            "ایالات متحده، آلمان، بریتانیا، ایتالیا، فرانسه، کانادا، چین و روسیه",
            "ایالات متحده، آلمان، بریتانیا، ژاپن، کانادا، روسیه، فرانسه و چین",
            "ایالات متحده، بریتانیا، ژاپن، کانادا، استرالیا، روسیه، فرانسه و چین",
            "ایالات متحده، آلمان، بریتانیا، ایتالیا، فرانسه، ژاپن، کانادا و روسیه",
        ],
        "correct": 3,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "The G8 traditionally included the United States, Germany, the United Kingdom, Italy, France, Japan, Canada and Russia.",
    },
    {
        "q": "How much merchandise trade was involved within NAFTA in 2008?",
        "q_fa": "در سال ۲۰۰۸ حجم تجارت کالا در چارچوب NAFTA چقدر بود؟",
        "q_fr": "Quel volume d'échanges de marchandises l'ALENA (NAFTA) représentait-il en 2008?",
        "options": [
            "About $100 billion",
            "Over $1 trillion",
            "About $500 billion",
            "Over $100 trillion",
        ],
        "options_fr": [
            "Environ 100 milliards de dollars",
            "Plus d'un billion de dollars (trillion)",
            "Environ 500 milliards de dollars",
            "Plus de 100 billions de dollars",
        ],
        "options_fa": [
            "حدود ۱۰۰ میلیارد دلار",
            "بیش از ۱ تریلیون دلار",
            "حدود ۵۰۰ میلیارد دلار",
            "بیش از ۱۰۰ تریلیون دلار",
        ],
        "correct": 1,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "NAFTA created one of the largest trading blocs; merchandise trade among members exceeded one trillion U.S. dollars in 2008.",
    },
    {
        "q": "What is the G8?",
        "q_fa": "G8 چیست؟",
        "q_fr": "Qu'est-ce que le G8?",
        "options": [
            "A group of 8 leading industrialized countries",
            "The 8 countries involved in NAFTA",
            "The group of 8 Fathers of Confederation",
            "A group of 8 famous Canadian artists",
        ],
        "options_fr": [
            "Un groupe de huit grandes nations industrialisées",
            "Les huit pays de l'ALENA",
            "Les huit Pères de la Confédération",
            "Huit artistes canadiens célèbres",
        ],
        "options_fa": [
            "گروهی از ۸ کشور پیشرو صنعتی",
            "۸ کشور عضو NAFTA",
            "گروه ۸ پدر بنیان‌گذار فدراسیون",
            "گروهی از ۸ هنرمند مشهور کانادایی",
        ],
        "correct": 0,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "The G8 was a forum of leading industrialized democracies.",
    },
    {
        "q": "Which industries make products to sell in Canada and around the world?",
        "q_fa": "کدام صنایع کالا برای فروش در کانادا و سراسر جهان تولید می‌کنند؟",
        "q_fr": "Quelles industries fabriquent des produits à vendre au Canada et dans le monde?",
        "options": [
            "Service industries",
            "Manufacturing industries",
            "Natural resources industries",
            "Trading industries",
        ],
        "options_fr": [
            "Industries des services",
            "Industries manufacturières",
            "Industries des ressources naturelles",
            "Industries du commerce",
        ],
        "options_fa": [
            "صنایع خدماتی",
            "صنایع تولیدی",
            "صنایع منابع طبیعی",
            "صنایع تجاری",
        ],
        "correct": 1,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "Manufacturing industries produce goods for domestic and international markets.",
    },
    {
        "q": "To which industries do transportation, education, health care, construction, banking, communications, retail services, tourism and government belong?",
        "q_fa": "حمل‌ونقل، آموزش، بهداشت، ساخت‌وساز، بانکداری، ارتباطات، خرده‌فروشی، گردشگری و دولت به کدام صنعت تعلق دارند؟",
        "q_fr": "À quelles industries appartiennent les transports, l'éducation, la santé, la construction, la banque, les communications, le commerce de détail, le tourisme et le gouvernement?",
        "options": [
            "Manufacturing industries",
            "Natural resources industries",
            "Service industries",
            "Trading industries",
        ],
        "options_fr": [
            "Industries manufacturières",
            "Industries des ressources naturelles",
            "Industries des services",
            "Industries du commerce",
        ],
        "options_fa": [
            "صنایع تولیدی",
            "صنایع منابع طبیعی",
            "صنایع خدماتی",
            "صنایع تجاری",
        ],
        "correct": 2,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "Examples of service industries include transportation, education, health care, construction, banking, communications, retail, tourism and government.",
    },
    {
        "q": "To which industries do products such as paper, high technology equipment, aerospace technology, automobiles, machinery, food and clothing belong?",
        "q_fa": "کالاهایی مانند کاغذ، تجهیزات فناوری پیشرفته، فناوری هوافضا، خودرو، ماشین‌آلات، غذا و پوشاک به کدام صنعت تعلق دارند؟",
        "q_fr": "À quelles industries appartiennent le papier, les équipements de haute technologie, l'aérospatial, les automobiles, les machines, l'alimentation et l'habillement?",
        "options": [
            "Service industries",
            "Manufacturing industries",
            "Natural resources industries",
            "Trading industries",
        ],
        "options_fr": [
            "Industries des services",
            "Industries manufacturières",
            "Industries des ressources naturelles",
            "Industries du commerce",
        ],
        "options_fa": [
            "صنایع خدماتی",
            "صنایع تولیدی",
            "صنایع منابع طبیعی",
            "صنایع تجاری",
        ],
        "correct": 1,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "Manufacturing industries make products such as paper, high-tech equipment, aerospace, automobiles, machinery, food and clothing.",
    },
    {
        "q": "To which industries do forestry, fishing, agriculture, mining and energy belong?",
        "q_fa": "جنگلداری، ماهیگیری، کشاورزی، معدن و انرژی به کدام صنعت تعلق دارند؟",
        "q_fr": "À quelles industries appartiennent la foresterie, la pêche, l'agriculture, l'exploitation minière et l'énergie?",
        "options": [
            "Service industries",
            "Manufacturing industries",
            "Trading industries",
            "Natural resources industries",
        ],
        "options_fr": [
            "Industries des services",
            "Industries manufacturières",
            "Industries du commerce",
            "Industries des ressources naturelles",
        ],
        "options_fa": [
            "صنایع خدماتی",
            "صنایع تولیدی",
            "صنایع تجاری",
            "صنایع منابع طبیعی",
        ],
        "correct": 3,
        "page": 42,
        "section": "Canada's Economy",
        "book_text": "Natural resources industries include forestry, fishing, agriculture, mining and energy.",
    },
]

OUT.write_text(json.dumps(rows, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print("Wrote", OUT, "n=", len(rows))
