# Run: python scripts/_gen_chapter10_regions_json.py
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "static" / "chapter10_canada_regions_questions.json"

# (q_en, options_en, correct_0based, page, book_text, q_fa, q_fr)
# options_fr / options_fa default to English place names where identical; override via _opts_fr/_opts_fa None = use opts

def row(q, opts, cor, page, book, qfa, qfr, opts_fr=None, opts_fa=None):
    ofr = opts_fr if opts_fr is not None else list(opts)
    ofa = opts_fa if opts_fa is not None else list(opts)
    return {
        "q": q,
        "q_fa": qfa,
        "q_fr": qfr,
        "options": list(opts),
        "options_fr": ofr,
        "options_fa": ofa,
        "correct": cor,
        "page": page,
        "section": "Canada's Regions",
        "book_text": book,
    }

ROWS = [
    row(
        "In terms of size, how does Canada rank?",
        ["Second largest country on earth", "First largest country on earth", "Third largest country on earth", "Fourth largest country on earth"],
        0,
        44,
        "Canada is the world's second-largest country in total area.",
        "از نظر مساحت، کانادا در چه رتبه‌ای در جهان قرار دارد؟",
        "Comment le Canada se classe-t-il en superficie?",
        None,
        ["دومین کشور بزرگ جهان", "بزرگ‌ترین کشور جهان", "سومین کشور بزرگ جهان", "چهارمین کشور بزرگ جهان"],
    ),
    row(
        "Which oceans line Canada's frontiers?",
        ["Pacific Ocean, Atlantic Ocean and Southern Ocean", "Atlantic Ocean and Pacific Ocean", "Pacific Ocean, Atlantic Ocean and Arctic Ocean", "Pacific Ocean and Arctic Ocean"],
        2,
        44,
        "Canada borders the Pacific, Atlantic and Arctic oceans.",
        "کدام اقیانوس‌ها مرزهای کانادا را دربر می‌گیرند؟",
        "Quels océans bordent le Canada?",
        ["Océan Pacifique, Atlantique et Austral", "Océans Atlantique et Pacifique", "Océans Pacifique, Atlantique et Arctique", "Océans Pacifique et Arctique"],
        ["اقیانوس آرام، اقیانوس اطلس و اقیانوس جنوبی", "اقیانوس اطلس و اقیانوس آرام", "اقیانوس آرام، اقیانوس اطلس و اقیانوس شمالگان", "اقیانوس آرام و اقیانوس شمالگان"],
    ),
    row(
        "Which country lies on Canada's southern border?",
        ["Mexico", "U.S.A.", "Central America", "Washington"],
        1,
        44,
        "The United States of America (U.S.A.) is Canada's southern neighbour.",
        "کدام کشور در جنوب کانادا قرار دارد؟",
        "Quel pays est situé à la frontière sud du Canada?",
        None,
        ["مکزیک", "ایالات متحدهٔ آمریکا", "آمریکای مرکزی", "واشینگتن"],
    ),
    row(
        "What are the regions of Canada?",
        [
            "Atlantic Provinces, Central Canada, Prairie Provinces, West Coast and Northern Territories",
            "South Provinces, Northern Canada, West Provinces, East Provinces, and Central Territories",
            "Ontario, Quebec, Prairie Provinces and Central Canada",
            "Atlantic Provinces, Central Canada, Prairie Provinces, and West Coast",
        ],
        0,
        44,
        "Canada is often described in regions: Atlantic, Central Canada, the Prairies, the West Coast and the North.",
        "نواحی (مناطق) کانادا کدامند؟",
        "Quelles sont les grandes régions du Canada?",
        None,
        [
            "استان‌های آتلانتیک، کانادای مرکزی، استان‌های دشت، ساحل غربی و سرزمین‌های شمالی",
            "استان‌های جنوبی، کانادای شمالی، غرب، شرق و سرزمین‌های مرکزی",
            "انتاریو، کبک، دشت‌ها و کانادای مرکزی",
            "استان‌های آتلانتیک، کانادای مرکزی، دشت‌ها و ساحل غربی",
        ],
    ),
    row(
        "What is Canada's national capital?",
        ["Ottawa", "Toronto", "Vancouver", "Montreal"],
        0,
        44,
        "Ottawa is Canada's capital city.",
        "پایتخت ملی کانادا کجاست؟",
        "Quelle est la capitale nationale du Canada?",
        None,
        ["اتاوا", "تورنتو", "ونکوور", "مونترال"],
    ),
    row(
        "When was Ottawa chosen as the capital of Canada?",
        ["1757", "1957", "1857", "1657"],
        2,
        44,
        "Queen Victoria chose Ottawa as the capital of the Province of Canada in 1857.",
        "اتاوا در چه زمانی به‌عنوان پایتخت کانادا برگزیده شد؟",
        "En quelle année Ottawa a-t-elle été choisie comme capitale?",
        None,
        ["۱۷۵۷", "۱۹۵۷", "۱۸۵۷", "۱۶۵۷"],
    ),
    row(
        "In terms of size, how does Ottawa's metropolitan area rank in Canada?",
        ["Fourth largest metropolitan area", "Largest metropolitan area", "Second largest metropolitan area", "Third largest metropolitan area"],
        0,
        44,
        "The Ottawa metropolitan area is among Canada's largest urban regions (often cited as fourth).",
        "منطقهٔ شهری اتاوا از نظر وسعت در کانادا چندم است؟",
        "Comment la région métropolitaine d'Ottawa se classe-t-elle par taille au Canada?",
        None,
        ["چهارمین ناحیهٔ شهری بزرگ", "بزرگ‌ترین ناحیهٔ شهری", "دومین ناحیهٔ شهری بزرگ", "سومین ناحیهٔ شهری بزرگ"],
    ),
    row(
        "How many provinces and territories are there in Canada?",
        ["Ten provinces and four territories", "Nine provinces and three territories", "Ten provinces and three territories", "Eight provinces and five territories"],
        2,
        44,
        "Canada has ten provinces and three territories.",
        "کانادا چند استان و چند قلمرو دارد؟",
        "Combien de provinces et de territoires compte le Canada?",
        None,
        ["ده استان و چهار قلمرو", "نه استان و سه قلمرو", "ده استان و سه قلمرو", "هشت استان و پنج قلمرو"],
    ),
    row(
        "In Canada, each province and territory has its own capital city.",
        ["True", "False", "Only provinces have capitals", "Only territories have capitals"],
        0,
        44,
        "Each province and territory has its own capital city.",
        "در کانادا هر استان و قلمرو پایتخت مخصوص خود را دارد.",
        "Au Canada, chaque province et territoire a sa propre capitale.",
        ["Vrai", "Faux", "Seules les provinces ont une capitale", "Seuls les territoires ont une capitale"],
        ["درست", "نادرست", "فقط استان‌ها پایتخت دارند", "فقط قلمروها پایتخت دارند"],
    ),
    row(
        "What is the population of Canada?",
        ["About 42 million people", "About 34 million people", "About 18 million people", "About 68 million people"],
        1,
        44,
        "Discover Canada study materials have cited a population of about 34 million (figures change over time).",
        "جمعیت کانادا چقدر است؟",
        "Quelle est la population du Canada?",
        None,
        ["حدود ۴۲ میلیون نفر", "حدود ۳۴ میلیون نفر", "حدود ۱۸ میلیون نفر", "حدود ۶۸ میلیون نفر"],
    ),
    row(
        "Where do the majority of Canadians live?",
        ["In rural areas", "In small towns", "In cities", "Along the East Coast"],
        2,
        44,
        "The majority of Canadians live in urban areas (cities).",
        "اکثر کانادایی‌ها کجا زندگی می‌کنند؟",
        "Où vit la majorité des Canadiens?",
        None,
        ["در مناطق روستایی", "در شهرهای کوچک", "در شهرها", "در امتداد سواحل شرقی"],
    ),
    row(
        "Which of the following defines Central Canada?",
        ["Quebec and Ontario", "Quebec and Manitoba", "Ontario and Saskatchewan", "Manitoba and Saskatchewan"],
        0,
        45,
        "Central Canada consists of Quebec and Ontario.",
        "کدام گزینه «کانادای مرکزی» را تعریف می‌کند؟",
        "Laquelle des propositions suivantes définit le Canada central?",
        None,
        ["کبک و انتاریو", "کبک و مانیتوبا", "انتاریو و ساسکاچوان", "مانیتوبا و ساسکاچوان"],
    ),
    row(
        "Which of the following are Prairie Provinces?",
        ["Manitoba, Saskatchewan and Alberta", "Saskatchewan, Alberta and Nova Scotia", "Ontario, Manitoba and Alberta", "Manitoba, Ontario and Saskatchewan"],
        0,
        45,
        "The Prairie Provinces are Manitoba, Saskatchewan and Alberta.",
        "کدام‌ها «استان‌های دشت» (Prairie Provinces) هستند؟",
        "Lesquelles sont les provinces des Prairies?",
        None,
        ["مانیتوبا، ساسکاچوان و آلبرتا", "ساسکاچوان، آلبرتا و نوا اسکوشیا", "انتاریو، مانیتوبا و آلبرتا", "مانیتوبا، انتاریو و ساسکاچوان"],
    ),
    row(
        "Which of the following is a West Coast Province?",
        ["Nunavut", "Nova Scotia", "British Columbia", "Alberta"],
        2,
        45,
        "British Columbia is Canada's Pacific/West Coast province.",
        "کدام یک استان ساحل غربی است؟",
        "Laquelle est une province de la côte Ouest?",
        None,
        ["نوناووت", "نوا اسکوشیا", "بریتیش کلمبیا", "آلبرتا"],
    ),
    row(
        "Which of the following defines Northern Canada?",
        ["Nunavut, Northwest Territories and Yukon", "Nunavut and Northwest Territories", "Northwest Territories and Yukon", "Nunavut, Northwest Territories and Newfoundland"],
        0,
        45,
        "Northern Canada comprises Nunavut, the Northwest Territories and Yukon.",
        "کدام گزینه «شمال کانادا» را تعریف می‌کند؟",
        "Laquelle définit le Nord du Canada?",
        None,
        ["نوناووت، سرزمین‌های شمال غرب و یوکان", "نوناووت و سرزمین‌های شمال غرب", "سرزمین‌های شمال غرب و یوکان", "نوناووت، شمال‌غرب و نیوفاندلند و لابرادور"],
    ),
    row(
        "What is the capital of Newfoundland and Labrador?",
        ["St. John's", "Charlottetown", "Halifax", "Fredericton"],
        0,
        45,
        "The capital of Newfoundland and Labrador is St. John's.",
        "پایتخت نیوفاندلند و لابرادور کجاست؟",
        "Quelle est la capitale de Terre-Neuve-et-Labrador?",
        None,
        ["سنت جانز", "شارلوت‌تاون", "هلیفکس", "فردریکتون"],
    ),
    row(
        "What is the capital of New Brunswick?",
        ["Halifax", "Fredericton", "Winnipeg", "Regina"],
        1,
        45,
        "The capital of New Brunswick is Fredericton.",
        "پایتخت نیوبرانزویک کجاست؟",
        "Quelle est la capitale du Nouveau-Brunswick?",
        None,
        ["هلیفکس", "فردریکتون", "وینیپگ", "رجاینا"],
    ),
    row(
        "What is the capital of Quebec?",
        ["Quebec City", "Montreal", "Saint-Jean", "Chicoutimi"],
        0,
        45,
        "The capital of Quebec is Québec City.",
        "پایتخت کبک کجاست؟",
        "Quelle est la capitale du Québec?",
        None,
        ["شهر کبک", "مونترال", "سن ژان", "شیکوتیمی"],
    ),
    row(
        "What is the capital of Ontario?",
        ["Ottawa", "Toronto", "Kingston", "Mississauga"],
        1,
        45,
        "The capital of Ontario is Toronto.",
        "پایتخت انتاریو کجاست؟",
        "Quelle est la capitale de l'Ontario?",
        None,
        ["اتاوا", "تورنتو", "کینگستون", "میسیساگا"],
    ),
    row(
        "What is the capital of Manitoba?",
        ["Regina", "Edmonton", "Winnipeg", "Calgary"],
        2,
        45,
        "The capital of Manitoba is Winnipeg.",
        "پایتخت مانیتوبا کجاست؟",
        "Quelle est la capitale du Manitoba?",
        None,
        ["رجاینا", "ادمونتون", "وینیپگ", "کلگری"],
    ),
    row(
        "What is the capital of Alberta?",
        ["Calgary", "Edmonton", "Red Deer", "Regina"],
        1,
        45,
        "The capital of Alberta is Edmonton.",
        "پایتخت آلبرتا کجاست؟",
        "Quelle est la capitale de l'Alberta?",
        None,
        ["کلگری", "ادمونتون", "رد دیر", "رجاینا"],
    ),
    row(
        "What is the capital of British Columbia?",
        ["Vancouver", "Victoria", "Calgary", "Edmonton"],
        1,
        45,
        "The capital of British Columbia is Victoria.",
        "پایتخت بریتیش کلمبیا کجاست؟",
        "Quelle est la capitale de la Colombie-Britannique?",
        None,
        ["ونکوور", "ویکتوریا", "کلگری", "ادمونتون"],
    ),
    row(
        "What is the capital of the Northwest Territories?",
        ["Whitehorse", "Edmonton", "Yellowknife", "Iqaluit"],
        2,
        45,
        "The capital of the Northwest Territories is Yellowknife.",
        "پایتخت سرزمین‌های شمال غرب کجاست؟",
        "Quelle est la capitale des Territoires du Nord-Ouest?",
        None,
        ["وایت‌هورس", "ادمونتون", "یلو نایف", "ایکالویت"],
    ),
    row(
        "What is the capital of the Yukon?",
        ["Yellowknife", "Iqaluit", "Whitehorse", "Edmonton"],
        2,
        45,
        "The capital of Yukon is Whitehorse.",
        "پایتخت یوکان کجاست؟",
        "Quelle est la capitale du Yukon?",
        None,
        ["یلو نایف", "ایکالویت", "وایت‌هورس", "ادمونتون"],
    ),
    row(
        "Which of the following does not border British Columbia?",
        ["Saskatchewan", "Yukon", "Alberta", "Northwest Territories"],
        0,
        45,
        "British Columbia borders Yukon, the Northwest Territories, Alberta, the Pacific and Alaska (U.S.A.); it does not border Saskatchewan.",
        "کدام با بریتیش کلمبیا هم‌مرز نیست؟",
        "Laquelle ne borde pas la Colombie-Britannique?",
        None,
        ["ساسکاچوان", "یوکان", "آلبرتا", "سرزمین‌های شمال غرب"],
    ),
    row(
        "Which of the following does not border Alberta?",
        ["British Columbia", "Manitoba", "Saskatchewan", "Northwest Territories"],
        1,
        45,
        "Alberta borders British Columbia, Saskatchewan, the Northwest Territories and the U.S.A.; it does not border Manitoba.",
        "کدام با آلبرتا هم‌مرز نیست؟",
        "Laquelle ne borde pas l'Alberta?",
        None,
        ["بریتیش کلمبیا", "مانیتوبا", "ساسکاچوان", "سرزمین‌های شمال غرب"],
    ),
    row(
        "Which of the following does not border the Northwest Territories?",
        ["Yukon", "Ontario", "Nunavut", "Alberta"],
        1,
        45,
        "The Northwest Territories border Yukon, British Columbia, Alberta, Saskatchewan and Nunavut; Ontario does not border the NWT.",
        "کدام با سرزمین‌های شمال‌غرب هم‌مرز نیست؟",
        "Laquelle ne borde pas les Territoires du Nord-Ouest?",
        None,
        ["یوکان", "انتاریو", "نوناووت", "آلبرتا"],
    ),
    row(
        "Which of the following does not border Manitoba?",
        ["Quebec", "Saskatchewan", "Ontario", "U.S.A."],
        0,
        45,
        "Manitoba borders Saskatchewan, Ontario, Nunavut and the U.S.A.; it does not border Quebec.",
        "کدام با مانیتوبا هم‌مرز نیست؟",
        "Laquelle ne borde pas le Manitoba?",
        None,
        ["کبک", "ساسکاچوان", "انتاریو", "ایالات متحده"],
    ),
    row(
        "Which of the following does not border Ontario?",
        ["Nova Scotia", "Manitoba", "Quebec", "Hudson Bay"],
        0,
        45,
        "Ontario borders Manitoba, Quebec, Hudson Bay and the U.S.A.; Nova Scotia does not border Ontario.",
        "کدام با انتاریو هم‌مرز نیست؟",
        "Laquelle ne borde pas l'Ontario?",
        None,
        ["نوا اسکوشیا", "مانیتوبا", "کبک", "خلیج هادسون"],
    ),
    row(
        "Which of the following does not border Quebec?",
        ["Ontario", "New Brunswick", "Nova Scotia", "Atlantic Ocean"],
        2,
        45,
        "Quebec borders Ontario, New Brunswick, Newfoundland and Labrador and the U.S.A.; Nova Scotia does not share a land border with Quebec.",
        "کدام با کبک هم‌مرز نیست؟",
        "Laquelle ne borde pas le Québec?",
        None,
        ["انتاریو", "نیوبرانزویک", "نوا اسکوشیا", "اقیانوس اطلس"],
    ),
    row(
        "Which of the following does not border New Brunswick?",
        ["Nova Scotia", "Prince Edward Island", "Quebec", "Atlantic Ocean"],
        1,
        45,
        "New Brunswick borders Nova Scotia, Quebec and the U.S.A.; Prince Edward Island is linked by bridge but is not a land neighbour in the same sense as the distractors used in many practice tests.",
        "کدام با نیوبرانزویک هم‌مرز نیست؟",
        "Laquelle ne borde pas le Nouveau-Brunswick?",
        None,
        ["نوا اسکوشیا", "جزیرهٔ پرنس ادوارد", "کبک", "اقیانوس اطلس"],
    ),
    row(
        "Which of the following borders Nova Scotia?",
        ["New Brunswick", "Quebec", "Prince Edward Island", "Ontario"],
        0,
        45,
        "Nova Scotia borders New Brunswick.",
        "کدام با نوا اسکوشیا هم‌مرز است؟",
        "Laquelle borde la Nouvelle-Écosse?",
        None,
        ["نیوبرانزویک", "کبک", "جزیرهٔ پرنس ادوارد", "انتاریو"],
    ),
    row(
        "Which of the following borders Newfoundland and Labrador?",
        ["Quebec", "Nova Scotia", "New Brunswick", "Ontario"],
        0,
        45,
        "Newfoundland and Labrador borders Quebec (Labrador).",
        "کدام با نیوفاندلند و لابرادور هم‌مرز است؟",
        "Laquelle borde Terre-Neuve-et-Labrador?",
        None,
        ["کبک", "نوا اسکوشیا", "نیوبرانزویک", "انتاریو"],
    ),
    row(
        "Which of the following provinces/territories borders the Pacific Ocean?",
        ["Quebec", "British Columbia", "Northwest Territories", "Alberta"],
        1,
        45,
        "British Columbia borders the Pacific Ocean.",
        "کدام استان/قلمرو به اقیانوس آرام می‌رسد؟",
        "Laquelle borde l'océan Pacifique?",
        None,
        ["کبک", "بریتیش کلمبیا", "سرزمین‌های شمال غرب", "آلبرتا"],
    ),
    row(
        "Which of the following provinces/territories does not border the U.S.A.?",
        ["Quebec", "British Columbia", "Nunavut", "Alberta"],
        2,
        45,
        "Nunavut has no land border with the contiguous United States (practice-test framing).",
        "کدام استان/قلمرو با ایالات متحده هم‌مرز نیست؟",
        "Laquelle ne borde pas les États-Unis?",
        None,
        ["کبک", "بریتیش کلمبیا", "نوناووت", "آلبرتا"],
    ),
    row(
        "Which of the following provinces/territories borders with the Atlantic Ocean?",
        ["Newfoundland and Labrador", "British Columbia", "Manitoba", "Ontario"],
        0,
        45,
        "Newfoundland and Labrador borders the Atlantic Ocean.",
        "کدام به اقیانوس اطلس می‌رسد؟",
        "Laquelle borde l'océan Atlantique?",
        None,
        ["نیوفاندلند و لابرادور", "بریتیش کلمبیا", "مانیتوبا", "انتاریو"],
    ),
    row(
        "Which of the following provinces/territories borders the Arctic Ocean?",
        ["Nunavut", "Manitoba", "Ontario", "Newfoundland and Labrador"],
        0,
        45,
        "Nunavut includes extensive Arctic coastline.",
        "کدام به اقیانوس شمالگان می‌رسد؟",
        "Laquelle borde l'océan Arctique?",
        None,
        ["نوناووت", "مانیتوبا", "انتاریو", "نیوفاندلند و لابرادور"],
    ),
    row(
        "Which province has its own time zone?",
        ["Nunavut", "Yukon", "Newfoundland and Labrador", "Prince Edward Island"],
        2,
        46,
        "Newfoundland and Labrador has its own time zone (Newfoundland Time).",
        "کدام استان منطقهٔ زمانی مخصوص خود را دارد؟",
        "Quelle province a son propre fuseau horaire?",
        None,
        ["نوناووت", "یوکان", "نیوفاندلند و لابرادور", "جزیرهٔ پرنس ادوارد"],
    ),
    row(
        "What is the oldest colony of the British Empire?",
        ["Prince Edward Island", "Newfoundland and Labrador", "Nova Scotia", "New Brunswick"],
        1,
        46,
        "Newfoundland and Labrador was the oldest colony of the British Empire in what is now Canada.",
        "قدیمی‌ترین مستعمرهٔ امپراتوری بریتانیا کدام است؟",
        "Quelle est la plus ancienne colonie de l'Empire britannique (selon le guide)?",
        None,
        ["جزیرهٔ پرنس ادوارد", "نیوفاندلند و لابرادور", "نوا اسکوشیا", "نیوبرانزویک"],
    ),
    row(
        "Which province has long been known for its fisheries, coastal fishing villages and distinct culture?",
        ["Newfoundland and Labrador", "Nova Scotia", "New Brunswick", "British Columbia"],
        0,
        46,
        "Newfoundland and Labrador is known for fisheries, coastal communities and distinct culture.",
        "کدام استان به ماهیگیری، روستاهای ساحلی و فرهنگ متمایز شهرت دارد؟",
        "Quelle province est réputée pour ses pêcheries et villages côtiers?",
        None,
        ["نیوفاندلند و لابرادور", "نوا اسکوشیا", "نیوبرانزویک", "بریتیش کلمبیا"],
    ),
    row(
        "What does P.E.I. stand for?",
        ["Prince Edward Island", "Prince Edmond Island", "Port Edward Island", "Prince Edgar Island"],
        0,
        46,
        "P.E.I. stands for Prince Edward Island.",
        "مخفف P.E.I. چیست؟",
        "Que signifie « P.E.I. »?",
        None,
        ["جزیرهٔ پرنس ادوارد", "جزیرهٔ پرنس ادموند", "بندر ادوارد", "جزیرهٔ پرنس ادگار"],
    ),
    row(
        "What is Canada's smallest province?",
        ["Nunavut", "Prince Edward Island", "Saskatchewan", "Nova Scotia"],
        1,
        46,
        "Prince Edward Island is Canada's smallest province (by land area).",
        "کوچک‌ترین استان کانادا کدام است؟",
        "Quelle est la plus petite province du Canada?",
        None,
        ["نوناووت", "جزیرهٔ پرنس ادوارد", "ساسکاچوان", "نوا اسکوشیا"],
    ),
    row(
        "In Canada, where can you find one of the longest continuous multispan bridges in the world?",
        ["Prince Edward Island", "Quebec", "Nova Scotia", "Ontario"],
        0,
        46,
        "The Confederation Bridge links Prince Edward Island to the mainland.",
        "یکی از درازترین پل‌های چندپلّهٔ جهان در کانادا کجاست؟",
        "Où trouve-t-on l'un des plus longs ponts à travées continues au Canada?",
        None,
        ["جزیرهٔ پرنس ادوارد", "کبک", "نوا اسکوشیا", "انتاریو"],
    ),
    row(
        "In Canada, where can you find Celtic and Gaelic traditions?",
        ["Newfoundland and Labrador", "Saskatchewan", "Nova Scotia", "Prince Edward Island"],
        2,
        46,
        "Nova Scotia has strong Celtic and Gaelic cultural traditions.",
        "سنت‌های سلتی و گیلیک در کانادا بیشتر کجا یافت می‌شود؟",
        "Où trouve-t-on des traditions celtiques et gaéliques?",
        None,
        ["نیوفاندلند و لابرادور", "ساسکاچوان", "نوا اسکوشیا", "جزیرهٔ پرنس ادوارد"],
    ),
    row(
        "Where is Canada's largest naval base?",
        ["Nova Scotia", "Vancouver", "New Brunswick", "Ontario"],
        0,
        46,
        "Canada's largest naval base is in Halifax, Nova Scotia.",
        "بزرگ‌ترین پایگاه دریایی کانادا کجاست؟",
        "Où se trouve la plus grande base navale du Canada?",
        None,
        ["نوا اسکوشیا", "ونکوور", "نیوبرانزویک", "انتاریو"],
    ),
    row(
        "Where is Canada's largest east coast port?",
        ["Charlottetown", "St. John's", "Halifax", "Fredericton"],
        2,
        46,
        "Halifax is a major Atlantic port and Canada's largest east coast port.",
        "بزرگ‌ترین بندر ساحل شرقی کانادا کجاست؟",
        "Où se trouve le plus grand port de la côte Est du Canada?",
        None,
        ["شارلوت‌تاون", "سنت جانز", "هلیفکس", "فردریکتون"],
    ),
    row(
        "In Canada, where can you find the world's highest tides?",
        ["Prince Edward Island", "Quebec", "Nova Scotia", "British Columbia"],
        2,
        46,
        "The Bay of Fundy in Nova Scotia has the world's highest tides.",
        "بلندترین جزر و مد جهان در کانادا کجاست؟",
        "Où trouve-t-on les plus grandes marées du monde?",
        None,
        ["جزیرهٔ پرنس ادوارد", "کبک", "نوا اسکوشیا", "بریتیش کلمبیا"],
    ),
    row(
        "Which province has the second largest river system on North America's Atlantic coastline?",
        ["Quebec", "Nova Scotia", "New Brunswick", "Newfoundland and Labrador"],
        2,
        46,
        "New Brunswick's Saint John River system is often cited in study materials in this context.",
        "کدام استان دومین سیستم رودخانه‌ای بزرگ در سواحل اطلس آمریکای شمالی را دارد؟",
        "Quelle province a le deuxième plus grand réseau fluvial sur la côte atlantique?",
        None,
        ["کبک", "نوا اسکوشیا", "نیوبرانزویک", "نیوفاندلند و لابرادور"],
    ),
    row(
        "Which city is the principal Francophone Acadian centre in Canada?",
        ["Moncton", "Quebec City", "Montreal", "Charlottetown"],
        0,
        47,
        "Moncton, New Brunswick, is a major Francophone Acadian centre.",
        "کدام شهر مرکز اصلی آکادیان فرانسوی‌زبان در کاناداست؟",
        "Quelle ville est le principal centre acadien francophone?",
        None,
        ["مانکتون", "شهر کبک", "مونترال", "شارلوت‌تاون"],
    ),
    row(
        "Which province is the only officially bilingual province?",
        ["Quebec", "New Brunswick", "Nova Scotia", "Ontario"],
        1,
        47,
        "New Brunswick is Canada's only officially bilingual province.",
        "کدام استان تنها استان رسمی دوزبانه است؟",
        "Quelle province est la seule province officiellement bilingue?",
        None,
        ["کبک", "نیوبرانزویک", "نوا اسکوشیا", "انتاریو"],
    ),
]

assert len(ROWS) == 50, len(ROWS)

OUT.write_text(json.dumps(ROWS, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print("Wrote", OUT, "n=", len(ROWS))
